up

diff --git a/home/.chezmoiscripts/darwin/run_onchange_after_bootstrap.sh.tmpl b/home/.chezmoiscripts/darwin/run_onchange_after_bootstrap.sh.tmpl
--- a/home/.chezmoiscripts/darwin/run_onchange_after_bootstrap.sh.tmpl
+++ b/home/.chezmoiscripts/darwin/run_onchange_after_bootstrap.sh.tmpl
@@ -83,13 +83,25 @@ install_brew_packages() {
     echo "packages install done."
 }
 
+install_mise() {
+    if command -v mise >/dev/null; then
+        echo "mise already installed."
+    else
+        brew install mise
+    fi
+    mise i || echo "mise install failed."
+    mise activate --shims
+    mise activate ${SHELL:-zsh}
+    mise list
+    echo "mise setup completed."
+}
+
 echo "bootstrap start."
 install_xcode_command_line_tools
 install_rosetta
 install_homebrew
 install_brew_packages
-# ~/.config/mise/config.toml に記載されたパッケージをインストール
-mise install || echo "mise install failed."
+install_mise
 echo "bootstrap done."
 echo "--------------------------------"
 echo "zsh --version $(zsh --version)"
diff --git a/home/.chezmoiscripts/linux/run_onchange_after_cli.sh.tmpl b/home/.chezmoiscripts/linux/run_onchange_after_cli.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_onchange_after_cli.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_onchange_after_cli.sh.tmpl
@@ -76,14 +76,14 @@ install_mise() {
     mise --version >> ${HOME}/which || echo "mise not found" >> ${HOME}/which
 
     # ~/.config/mise/config.toml に記載されたパッケージをインストール
-    mise install || echo "mise install failed." >> ${HOME}/which
+    mise i || echo "mise install failed." >> ${HOME}/which
 
     mise activate --shims
-    mise activate bash
+    mise activate ${SHELL:-bash}
     mise list
     echo "mise setup completed."
 
-    for cmd in go cargo npm node bun cargo-binstall python; do
+    for cmd in go cargo npm node bun cargo-binstall python uv jq gh yq cmake ninja aqua act caddy cloudflared websocat ffmpeg yt-dlp; do
         command -v "$cmd" >> ${HOME}/which || echo "$cmd not found" >> ${HOME}/which
     done
 }
@@ -201,7 +201,7 @@ change_shell_to_zsh
 install_mise
 install_cargo_tools
 install_flatpak
-install_go_aqua
+# install_go_aqua
 install_mkcert
 
 cat ${HOME}/which && rm -f ${HOME}/which
