ii

diff --git a/home/.chezmoiscripts/darwin/run_onchange_after_bootstrap.sh.tmpl b/home/.chezmoiscripts/darwin/run_onchange_after_bootstrap.sh.tmpl
--- a/home/.chezmoiscripts/darwin/run_onchange_after_bootstrap.sh.tmpl
+++ b/home/.chezmoiscripts/darwin/run_onchange_after_bootstrap.sh.tmpl
@@ -91,9 +91,17 @@ install_mise() {
         mise --version || echo "mise install failed."
     fi
 
-    {{- range .packages.mise }}
-    mise use -g -y "{{ . }}" || echo "{{ . }} install failed."
-    {{- end }}
+    if [ -f ${HOME}/.config/mise/config.toml ]; then
+        mise install -g -y
+    else
+
+        {{ range .packages.mise }}
+
+        mise use -g -y "{{ . }}" || echo "{{ . }} install failed."
+
+        {{ end }}
+
+    fi
 
     mise activate --shims
     mise activate bash
diff --git a/home/.chezmoiscripts/linux/run_onchange_after_cli.sh.tmpl b/home/.chezmoiscripts/linux/run_onchange_after_cli.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_onchange_after_cli.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_onchange_after_cli.sh.tmpl
@@ -82,11 +82,17 @@ install_mise() {
     export PATH="${HOME}/.local/bin:${HOME}/.local/share/mise/shims:$PATH"
     mise --version >> ${HOME}/which || echo "mise not found" >> ${HOME}/which
 
-    {{ range .packages.mise }}
+    if [ -f ${HOME}/.config/mise/config.toml ]; then
+        mise install -g -y
+    else
 
-    mise use -g -y {{ . }} || echo "{{ . }} install failed."
+        {{ range .packages.mise }}
 
-    {{ end }}
+        mise use -g -y "{{ . }}" || echo "{{ . }} install failed."
+
+        {{ end }}
+
+    fi
 
     mise activate --shims
     mise activate bash
