scripts

diff --git a/.chezmoiscripts/run_once_before_bw_unlock.sh.tmpl b/.chezmoiscripts/run_once_before_bw_unlock.sh.tmpl
--- a/.chezmoiscripts/run_once_before_bw_unlock.sh.tmpl
+++ b/.chezmoiscripts/run_once_before_bw_unlock.sh.tmpl
@@ -85,11 +85,11 @@ bw_unlock() {
     # bw cli があればロック解除
     if command -v bw >/dev/null 2>&1; then
         bw login {{ .email }} ${MASTER} || echo "bw login failed."
-        echo "export BW_SESSION="$(bw unlock ${MASTER} --raw)"" > ${SESSION} || echo "bw unlock failed."
+        echo "export BW_SESSION="$(bw unlock ${MASTER} --raw)"" >> ${SESSION} || echo "bw unlock failed."
 
     elif [ -f ${BW} ]; then
         ${BW} login {{ .email }} ${MASTER} || echo "bw login failed."
-        echo "export BW_SESSION="$(${BW} unlock ${MASTER} --raw)"" > ${SESSION} || echo "bw unlock failed."
+        echo "export BW_SESSION="$(${BW} unlock ${MASTER} --raw)"" >> ${SESSION} || echo "bw unlock failed."
 
     else
         echo "bw cli not found."
diff --git a/.chezmoiscripts/run_onchange_bootstrap.sh.tmpl b/.chezmoiscripts/run_onchange_bootstrap.sh.tmpl
--- a/.chezmoiscripts/run_onchange_bootstrap.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_bootstrap.sh.tmpl
@@ -13,6 +13,7 @@ echo "--------------------------------"
 
 # .env の確認と作成
 echo ".env && ENV checking..."
+cat {{ .chezmoi.sourceDir }}/.env
 mise set
 echo "--------------------------------"
 env
@@ -39,6 +40,7 @@ echo "--------------------------------"
 echo "SSH Config ..."
 cat ~/.ssh/config
 echo "--------------------------------"
+
 {{- end }}
 
 {{- if ne .name "runner" }}
@@ -93,7 +95,7 @@ install_packages() {
     {{ range .packages.linux.cli -}}
 
     if ! dpkg -l | grep -q {{ . }}; then
-        sudo apt-get install -y {{ . }} && echo "{{ . }} installed." >> ${HOME}/which || echo "{{ . }} install failed." >> ${HOME}/which
+        sudo apt-get install -y {{ . }} && echo "{{ . }} installed." || echo "{{ . }} install failed."
     else
         echo "{{ . }} already installed." >> ${HOME}/which
     fi
