dd

diff --git a/run_once_before_age_decrypt.sh.tmpl b/run_once_before_age_decrypt.sh.tmpl
--- a/run_once_before_age_decrypt.sh.tmpl
+++ b/run_once_before_age_decrypt.sh.tmpl
@@ -1,48 +1,52 @@
 #! /usr/bin/env bash
 
 echo "run_once_before_age_decrypt.sh.tmpl"
-# パスフレーズで復号するので事前に用意
-# https://www.chezmoi.io/user-guide/frequently-asked-questions/encryption/
 echo "--------------------------------"
+# key.txt をパスフレーズで復号するので事前に用意
+# https://www.chezmoi.io/user-guide/frequently-asked-questions/encryption/
 
 # .chezmoi.toml.tmpl と合わせる
 identity="${HOME}/.config/chezmoi/key.txt"
+
 # age-keygen | age --armor --passphrase ${key_name} で生成したキーのファイル名
 key_name="key.txt.age"
 key_path="{{ .chezmoi.sourceDir }}/${key_name}"
 
 # age なければインストール
-age_install() {
-    echo "age install..."
+echo "age install..."
 
 {{ if eq .chezmoi.os "darwin" -}}
-    command -v age >/dev/null || brew install age || echo "age install failed"
+
+command -v age >/dev/null || brew install age || echo "age install failed"
 
 {{ else if eq .chezmoi.os "linux" -}}
-    command -v age >/dev/null || sudo apt-get install -y age || echo "age install failed"
+
+command -v age >/dev/null || sudo apt-get install -y age || echo "age install failed"
 
 {{ else -}}
-    echo "Your OS is {{ .chezmoi.os }}"
-    curl -sSL https://github.com/FiloSottile/age/releases/download/v1.1.2/age-v1.1.2-darwin-amd64.tar.gz | tar xz
+
+echo "Your OS is {{ .chezmoi.os }}"
+curl -sSL https://github.com/FiloSottile/age/releases/download/v1.1.2/age-v1.1.2-darwin-amd64.tar.gz | tar xz
 
 {{ end -}}
 
-    command -v age || echo "age command not found"
-    echo "--------------------------------"
-}
-age_install
+command -v age || echo "age command not found && exit 1"
+echo "--------------------------------"
 
 {{ if ne .name "runner" -}}
-    echo "key_path: ${key_path}..."
-    echo "identity: ${identity}..."
 
-    if [ ! -f ${identity} ]; then
-        mkdir -p ${HOME}/.config/chezmoi
-        echo "Please enter your age passphrase:"
-        chezmoi age decrypt --output "${identity}" --passphrase "${key_path}"
-        chmod 600 ${identity}
-    fi
-    echo "Decrypt-private-key complete."
-    echo "--------------------------------"
+echo "key_path: ${key_path}..."
+echo "identity: ${identity}..."
+
+# ~/.config/chezmoi/key.txt が存在しない場合は復号
+if [ ! -f ${identity} ]; then
+    mkdir -p ${HOME}/.config/chezmoi
+    echo "Please enter your age passphrase:"
+    chezmoi age decrypt --output "${identity}" --passphrase "${key_path}"
+    chmod 600 ${identity}
+fi
+
+echo "Decrypt-private-key complete."
+echo "--------------------------------"
 
 {{ end -}}
