fff

diff --git a/run_once_before_age_decrypt.sh.tmpl b/run_once_before_age_decrypt.sh.tmpl
--- a/run_once_before_age_decrypt.sh.tmpl
+++ b/run_once_before_age_decrypt.sh.tmpl
@@ -1,10 +1,9 @@
 #! /usr/bin/env bash
 
 echo "run_once_before_age_decrypt.sh.tmpl"
-echo "--------------------------------"
 # パスフレーズで復号するので事前に用意
 # https://www.chezmoi.io/user-guide/frequently-asked-questions/encryption/
-echo "Decrypt private key..."
+echo "--------------------------------"
 
 # .chezmoi.toml.tmpl と合わせる
 identity="${HOME}/.config/chezmoi/key.txt"
@@ -12,23 +11,26 @@ identity="${HOME}/.config/chezmoi/key.txt"
 key_name="key.txt.age"
 key_path="{{ .chezmoi.sourceDir }}/${key_name}"
 
-# age なければインストール
-echo "age install..."
+age_install() {
+    # age なければインストール
+    echo "age install..."
 {{ if eq .chezmoi.os "darwin" -}}
-command -v age >/dev/null || brew install age || echo "age install failed"
+    command -v age >/dev/null || brew install age || echo "age install failed"
 
 {{ else if eq .chezmoi.os "linux" -}}
-command -v age >/dev/null || sudo apt-get install -y age || echo "age install failed"
+    command -v age >/dev/null || sudo apt-get install -y age || echo "age install failed"
 
 {{ else -}}
-echo "Your OS is {{ .chezmoi.os }}"
-curl -sSL https://github.com/FiloSottile/age/releases/download/v1.1.2/age-v1.1.2-darwin-amd64.tar.gz | tar xz
+    echo "Your OS is {{ .chezmoi.os }}"
+    curl -sSL https://github.com/FiloSottile/age/releases/download/v1.1.2/age-v1.1.2-darwin-amd64.tar.gz | tar xz
 
 {{ end -}}
-command -v age || echo "age command not found"
-echo "--------------------------------"
+    command -v age || echo "age command not found"
+    echo "--------------------------------"
+}
 
-# パスフレーズで復号
+decrypt() {
+    # パスフレーズで復号
 {{ if ne .name "runner" -}}
     echo "key_path: ${key_path}..."
     echo "identity: ${identity}..."
@@ -42,6 +44,11 @@ echo "--------------------------------"
     echo "Decrypt-private-key complete."
     echo "--------------------------------"
 {{ end -}}
+}
 
-cat ${key_path} || echo "${key_path} not found."
-echo "--------------------------------"
+main() {
+    echo "Decrypt private key..."
+    age_install
+    decrypt
+}
+main
diff --git a/run_once_before_bw_unlock.sh.tmpl b/run_once_before_bw_unlock.sh.tmpl
--- a/run_once_before_bw_unlock.sh.tmpl
+++ b/run_once_before_bw_unlock.sh.tmpl
@@ -3,7 +3,6 @@
 echo "--------------------------------"
 echo "run_once_before_bw_unlock.sh.tmpl"
 echo "OS: {{ .chezmoi.os | quote }}"
-echo "before bitwarden cli install"
 cd ${HOME}
 echo "--------------------------------"
 
@@ -24,52 +23,58 @@ SESSION="{{ .chezmoi.sourceDir }}/.env"
 # マスターパスワードを暗号化
 # echo "${MASTER}" | chezmoi encrypt > {{ .chezmoi.sourceDir }}/shhh.txt
 
-# mise なければインストール
+mise_npm() {
+    # mise なければインストール
 {{ if eq .chezmoi.os "darwin" -}}
-    if ! command -v mise >/dev/null 2>&1; then
-        brew install mise
-    fi
+    command -v mise >/dev/null || brew install mise
     mise use -g node@${VERSION} -y && mise activate bash >/dev/null || echo "node install failed."
 
 {{ else if eq .chezmoi.os "linux" -}}
-    if ! command -v mise >/dev/null 2>&1; then
-        curl https://mise.run | sh
-    fi
+    command -v mise >/dev/null || curl https://mise.run | sh
     ${MISE} use -g node@${VERSION} -y && ${MISE} activate bash >/dev/null || echo "node install failed."
+
 {{ end -}}
-# mise shims のパスを通す
-export PATH="${SHIMS}/shims:${PATH}"
-echo "--------------------------------"
+    # mise shims のパスを通す
+    export PATH="${SHIMS}/shims:${PATH}"
+    echo "--------------------------------"
+}
 
-# npm で bitwarden cli をインストール
-if command -v npm >/dev/null 2>&1; then
-    npm install -g @bitwarden/cli || echo "bitwarden cli install failed."
+bw_install() {
+    # npm で bitwarden cli をインストール
+    if command -v npm >/dev/null 2>&1; then
+        npm install -g @bitwarden/cli || echo "bitwarden cli install failed."
 
-elif [ -f ${NPM} ]; then
-    ${NPM} install -g @bitwarden/cli || echo "bitwarden cli install failed."
+    elif [ -f ${NPM} ]; then
+        ${NPM} install -g @bitwarden/cli || echo "bitwarden cli install failed."
 
-else
-    echo "npm not found."
-fi
-echo "--------------------------------"
+    else
+        echo "npm not found."
+    fi
+    echo "--------------------------------"
+}
 
-# bw cli があればロック解除
-if command -v bw >/dev/null 2>&1; then
-    echo "export BW_SESSION="$(bw unlock ${MASTER:-} --raw)"" >> ${SESSION} || echo "bw unlock failed."
+bw_unlock() {
+    # bw cli があればロック解除
+    if command -v bw >/dev/null 2>&1; then
+        echo "export BW_SESSION="$(bw unlock ${MASTER:-} --raw)"" >> ${SESSION} || echo "bw unlock failed."
 
-elif [ -f ${BW} ]; then
-    echo "export BW_SESSION="$(${BW} unlock ${MASTER:-} --raw)"" >> ${SESSION} || echo "bw unlock failed."
+    elif [ -f ${BW} ]; then
+        echo "export BW_SESSION="$(${BW} unlock ${MASTER:-} --raw)"" >> ${SESSION} || echo "bw unlock failed."
 
-else
-    echo "bw cli not found."
-    echo "export BW_SESSION=${BW_SESSION:-}" > ${SESSION}
-fi
-cat ${SESSION} || echo "${SESSION} not found."
-echo "--------------------------------"
+    else
+        echo "bw cli not found."
+    fi
 
-echo "PATH ..."
-echo "${PATH}" | tr ':' '\n'
-echo "--------------------------------"
-echo "export DOTFILES=${DOTFILES:-${HOME}/dotfiles}" >> ${SESSION}
-echo "bw install complete"
-echo "--------------------------------"
+    # .env 表示
+    cat ${SESSION} || echo "export BW_SESSION=${BW_SESSION:-}" > ${SESSION}
+    echo "--------------------------------"
+}
+
+main() {
+    echo "bitwarden setup"
+    mise_npm
+    bw_install
+    bw_unlock
+    echo "bitwarden setup complete"
+}
+main
