vvv

diff --git a/run_1_age.sh.tmpl b/run_1_age.sh.tmpl
--- a/run_1_age.sh.tmpl
+++ b/run_1_age.sh.tmpl
@@ -5,10 +5,14 @@ KEY_FILE=${HOME}/key.txt
 echo "KEY_FILE: ${KEY_FILE}"
 
 {{ if eq .chezmoi.os "darwin" -}}
-command -v age >/dev/null || brew install age || echo "age install failed"
+    command -v age >/dev/null || brew install age || echo "age install failed"
+{{ else if eq .chezmoi.os "linux" -}}
+    command -v age >/dev/null || sudo apt-get install -y age || echo "age install failed"
 {{ else -}}
-command -v age >/dev/null || sudo apt-get install -y age || echo "age install failed"
+    echo {{ .chezmoi.os | quote }}
+    curl -sSL https://github.com/FiloSottile/age/releases/download/v1.1.2/age-v1.1.2-darwin-amd64.tar.gz | tar xz
 {{ end }}
+
 
 if [ ! -f ${KEY_FILE} ]; then
     age-keygen -o ${KEY_FILE}
diff --git a/run_once_2_bootstrap.sh.tmpl b/run_once_2_bootstrap.sh.tmpl
--- a/run_once_2_bootstrap.sh.tmpl
+++ b/run_once_2_bootstrap.sh.tmpl
@@ -1,24 +1,34 @@
 #! /usr/bin/env bash
 
+USERNAME=$(whoami)
+
 echo "--------------------------------"
 echo "Welcome to my dotfiles!!"
-echo "whoami: $(whoami)"
+echo "dotfilesDir: {{ .dotfilesDir }}"
+echo "user: $USERNAME"
 echo "OS info ..."
 uname -a
-echo "$SHELL"
+echo "SHELL: $SHELL"
 echo "--------------------------------"
-echo "env ..."
+# .env の確認と作成
+echo ".env checking..."
+echo {{ .name | quote }}
+echo "export GIT_USER=$USERNAME" >>{{ .dotfilesDir }}/.env
+cat {{ .dotfilesDir }}/.env
 env
 echo "--------------------------------"
-echo "$PATH ..."
+echo "PATH ..."
 echo "$PATH" | tr ':' '\n'
 echo "--------------------------------"
 echo "SSH key ..."
-echo "$(cat /etc/ssh/sshd_config)"
+cat /etc/ssh/sshd_config
 ls -la ~/.ssh
-echo "$(cat ~/.ssh/id_ed25519.pub)"
+cat ~/.ssh/id_ed25519.pub
 echo "--------------------------------"
 echo "git config ..."
+cat ~/.config/git/user.conf
+git config --global user.name
+git config --global user.email
 git config --list
 git config --global commit.template ${HOME}/.config/git/commit.template
 echo "--------------------------------"
@@ -28,22 +38,21 @@ echo "--------------------------------"
 {{- if eq .chezmoi.os "linux" }}
 
     echo "Linux"
-    # ユーザー名を動的に取得
-    USER_NAME=$(whoami)
     # アーキテクチャを取得
     arch="$(dpkg --print-architecture)"
+
     # Zsh をデフォルトシェルに変更する関数
     change_shell_to_zsh() {
-            # zsh がインストールされているか確認
+        # zsh がインストールされているか確認
         command -v zsh >/dev/null || sudo apt-get install -y zsh || echo "zsh install failed." >> ${HOME}/which
+        # デフォルトシェルを変更
+        zsh_path=$(command -v zsh)
+        sudo chsh -s "${zsh_path}" "${USERNAME}" || echo "zsh default shell change failed." >> ${HOME}/which
+        command -v /bin/zsh >/dev/null || sudo ln -sf /usr/bin/zsh /bin/zsh
+        echo "Your shell is ${SHELL}"
+        echo "zsh default shell changed to ${zsh_path}."
+        command -v zsh >> ${HOME}/which || echo "zsh not found" >> ${HOME}/which
     }
-    # デフォルトシェルを変更
-    zsh_path=$(command -v zsh)
-    sudo chsh -s "${zsh_path}" "${USER_NAME}" || echo "zsh default shell change failed." >> ${HOME}/which
-    command -v /bin/zsh >/dev/null || sudo ln -sf /usr/bin/zsh /bin/zsh
-    echo "Your shell is ${SHELL}"
-    echo "zsh default shell changed to ${zsh_path}."
-    command -v zsh >> ${HOME}/which || echo "zsh not found" >> ${HOME}/which
 
     # 必要なパッケージをインストールする関数
     install_packages() {
@@ -60,57 +69,59 @@ echo "--------------------------------"
     }
 
     install_docker_compose() {
-        # 最新バージョンを取得
-        COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)
-        # ダウンロード URL の作成
-        COMPOSE_URL="https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)"
-        # Docker Compose のバイナリをダウンロード
-        sudo curl -L "$COMPOSE_URL" -o /usr/local/bin/docker-compose || echo "docker-compose download failed." >> ${HOME}/which
-        sudo chmod +x /usr/local/bin/docker-compose
-        echo "docker-compose install completed."
-        # シンボリックリンクを作成（必要に応じて）
-        if ! command -v docker-compose >/dev/null 2>&1; then
-            sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose || echo "docker-compose link failed." >> ${HOME}/which
+        if command -v docker-compose >/dev/null 2>&1; then
+            echo "docker-compose already installed."
+        else
+            # 最新バージョンを取得
+            COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)
+            # ダウンロード URL の作成
+            COMPOSE_URL="https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)"
+            # Docker Compose のバイナリをダウンロード
+            sudo curl -L "$COMPOSE_URL" -o /usr/local/bin/docker-compose || echo "docker-compose download failed." >> ${HOME}/which
+            sudo chmod +x /usr/local/bin/docker-compose
+            command -v docker compose >> ${HOME}/which || echo "docker-compose not found" >> ${HOME}/which
+           echo "docker-compose installed."
         fi
-        echo "docker-compose installed."
-        command -v docker compose >> ${HOME}/which || echo "docker-compose not found" >> ${HOME}/which
     }
 
     install_docker() {
-        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
-        echo "deb [arch=${arch} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
-        sudo apt-get update -y
-        sudo apt-get install -y docker-ce docker-ce-cli containerd.io || echo "docker install failed." >> ${HOME}/which
-        sudo chmod 666 /var/run/docker.sock
-        sudo groupadd -f docker
-        sudo usermod -aG docker "$USER_NAME"
-        sudo systemctl enable docker
-        docker info
-        command -v docker >> ${HOME}/which || echo "docker not found" >> ${HOME}/which
-        echo "docker daemon started."
+        if command -v docker >/dev/null 2>&1; then
+            echo "docker already installed."
+        else
+            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
+            echo "deb [arch=${arch} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
+            sudo apt-get update -y
+            sudo apt-get install -y docker-ce docker-ce-cli containerd.io || echo "docker install failed." >> ${HOME}/which
+            sudo chmod 666 /var/run/docker.sock
+            sudo groupadd -f docker
+            sudo usermod -aG docker "$USERNAME"
+            sudo systemctl enable docker
+            docker info
+            command -v docker >> ${HOME}/which || echo "docker not found" >> ${HOME}/which
+            echo "docker daemon started."
+        fi
     }
 
     # mise でインストールする関数
     install_mise() {
-        command -v mise >/dev/null || {
+        if ! command -v mise >/dev/null 2>&1; then
+            echo "mise install start..."
             curl https://mise.run | sh || {
                 sudo install -dm 755 /etc/apt/keyrings
                 wget -qO - https://mise.jdx.dev/gpg-key.pub | gpg --dearmor | sudo tee /etc/apt/keyrings/mise-archive-keyring.gpg 1>/dev/null
                 echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=${arch}] https://mise.jdx.dev/deb stable main" | sudo tee /etc/apt/sources.list.d/mise.list
                 sudo apt-get update -y && sudo apt-get install -y mise || echo "mise install failed." >> ${HOME}/which
             }
-        }
-        # .env ファイルを作成 (~/dotfiles を mise で設定してる関係)
-        echo "export USER_NAME=$(whoami)" >>.env
-        mise set
-        echo "mise installed."
-        echo "$(command -v mise)" >> ${HOME}/which
+        else
+            echo "mise already installed."
+        fi
+        command -v mise >> ${HOME}/which || echo "mise not found" >> ${HOME}/which
         # version 指定しないと arm64 でエラーになる
-        mise use -g starship@1.20.1 bun node@20 go -y --verbose || echo "mise use failed." >> ${HOME}/which
-        mise activate zsh
-        mise activate --shims
+        mise use -g bun go -y --verbose || echo "mise use failed." >> ${HOME}/which
+        mise activate bash || true
+        mise activate --shims || true
         echo "mise setup completed."
-        for cmd in starship bun node go; do
+        for cmd in starship bun go; do
             command -v "$cmd" >> ${HOME}/which || echo "$cmd not found" >> ${HOME}/which
         done
     }
@@ -123,26 +134,11 @@ echo "--------------------------------"
         command -v cargo >> ${HOME}/which || echo "cargo not found" >> ${HOME}/which
 
         echo "cargo tools install start..."
-        cargo install sheldon fd-find@9.0.0 xh bat || echo "cargo tools install failed." >> ${HOME}/which
+        cargo install starship@1.20.1 sheldon fd-find@9.0.0 xh bat || echo "cargo tools install failed." >> ${HOME}/which
         echo "cargo tools installed."
-        for cmd in sheldon fd-find xh bat; do
+        for cmd in starship sheldon fd-find xh bat; do
             command -v "$cmd" >> ${HOME}/which || echo "$cmd not found" >> ${HOME}/which
         done
-    }
-
-    # Bitwarden をインストールする関数
-    install_bitwarden() {
-        echo "bitwarden install start..."
-        command -v bw >/dev/null || {
-            if [ "${arch}" = "amd64" ]; then
-                sudo snap install bitwarden
-            else
-                bun install -g @bitwarden/cli
-                echo "export PATH=\"$HOME/.cache/.bun/bin:\$PATH\"" >> ${HOME}/.zshrc
-            fi
-        } || echo "bitwarden install failed." >> ${HOME}/which
-        echo "bitwarden installed."
-        command -v bw >> ${HOME}/which || echo "bitwarden not found" >> ${HOME}/which
     }
 
     install_flatpak() {
@@ -179,11 +175,18 @@ echo "--------------------------------"
     }
 
     install_act() {
-    echo "act install start..."
+        echo "act install start..."
         command -v act >/dev/null || curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash || echo "act install failed." >> ${HOME}/which
         sudo cp -r ./bin/act /usr/local/bin && sudo chmod +x /usr/local/bin/act
         echo "act installed."
         command -v act >> ${HOME}/which || echo "act not found" >> ${HOME}/which
+    }
+
+    install_volta() {
+        echo "volta install start..."
+        command -v volta >/dev/null || curl https://get.volta.sh | bash || echo "volta install failed." >> ${HOME}/which
+        echo "volta installed."
+        command -v volta >> ${HOME}/which || echo "volta not found" >> ${HOME}/which
     }
 
     install_cli_tools() {
@@ -192,12 +195,12 @@ echo "--------------------------------"
         install_packages
         change_shell_to_zsh
         install_mise
-        install_bitwarden
         install_docker
         install_docker_compose
         install_cargo_tools
         install_flatpak
         install_go_aqua
+        install_volta
         install_mkcert
         install_act
         install_multipass
@@ -249,7 +252,6 @@ echo "--------------------------------"
         else
             echo "specified Brewfile ($BREWFILE_PATH) not found. skip."
         fi
-        brew list
         brew --version
         brew install {{ .packages.darwin.brews | join " " }} || echo "brew install failed."
         brew update
@@ -257,6 +259,7 @@ echo "--------------------------------"
         brew autoremove
         brew cleanup
         brew doctor
+        brew list
         echo "packages install done."
     }
 
@@ -287,5 +290,4 @@ echo "--------------------------------"
 
 echo "--------------------------------"
 echo "zsh --version $(zsh --version)"
-echo "SHELL: $SHELL"
 echo "Package update && check done!!"
diff --git a/run_once_3_setup.sh.tmpl b/run_once_3_setup.sh.tmpl
--- a/run_once_3_setup.sh.tmpl
+++ b/run_once_3_setup.sh.tmpl
@@ -1,7 +1,9 @@
 #! /usr/bin/env bash
 
+echo "--------------------------------"
 echo "OS: {{ .chezmoi.os | quote }}"
 echo "desktop system setup"
+echo "--------------------------------"
 
 {{ if eq .chezmoi.os "darwin" -}}
     # コンピュータ名、ホスト名、ローカルホスト名、ユーザー名を設定
@@ -207,65 +209,86 @@ echo "desktop system setup"
 
     # Brave ブラウザをインストールする関数
     install_brave_browser() {
-        sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
-        echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
-        sudo apt-get update -y
-        sudo apt-get install -y brave-browser || echo "brave browser install failed."
-        echo "brave browser installed."
+        if ! command -v brave-browser >/dev/null 2>&1; then
+            sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
+            echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
+            sudo apt-get update -y
+            sudo apt-get install -y brave-browser || echo "brave browser install failed."
+            echo "brave browser installed."
+        else
+            echo "brave browser already installed."
+        fi
     }
 
     # Tabby Terminal をインストールする関数
     install_tabby_terminal() {
-        curl https://packagecloud.io/install/repositories/eugeny/tabby/script.deb.sh | sudo bash
-        sudo apt-get update -y
-        sudo apt-get install -y tabby-terminal || echo "tabby terminal install failed."
-        echo "tabby terminal installed."
+        if ! command -v tabby >/dev/null 2>&1; then
+            curl https://packagecloud.io/install/repositories/eugeny/tabby/script.deb.sh | sudo bash
+            sudo apt-get update -y
+            sudo apt-get install -y tabby-terminal || echo "tabby terminal install failed."
+            echo "tabby terminal installed."
+        else
+            echo "tabby terminal already installed."
+        fi
     }
 
     # Cloudflare Warp をインストールおよび設定する関数
     install_cloudflare_warp() {
-        sudo curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
-        echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
-        sudo apt-get update -y
-        sudo apt-get install -y cloudflare-warp || echo "cloudflare warp install failed."
-        warp-cli --accept-tos registration new
-        warp-cli --accept-tos mode warp
-        warp-cli --accept-tos dns families malware
-        warp-cli --accept-tos connect
-        warp-cli --accept-tos disconnect
-        echo "cloudflare warp installed."
+        if ! command -v warp-cli >/dev/null 2>&1; then
+            sudo curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
+            echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
+            sudo apt-get update -y
+            sudo apt-get install -y cloudflare-warp || echo "cloudflare warp install failed."
+            echo "cloudflare warp installed."
+
+            warp-cli --accept-tos registration new
+            warp-cli --accept-tos mode warp
+            warp-cli --accept-tos dns families malware
+            warp-cli --accept-tos connect
+            warp-cli --accept-tos disconnect
+        else
+            echo "cloudflare warp already installed."
+        fi
     }
 
     # GitHub Desktop と Cursor をインストールする関数
     install_github_desktop() {
-        sudo wget https://github.com/shiftkey/desktop/releases/download/release-3.4.3-linux1/GitHubDesktop-linux-${arch}-3.4.3-linux1.deb
-        sudo dpkg -i GitHubDesktop-linux-${arch}-3.4.3-linux1.deb || echo "github desktop install failed."
-        sudo rm -f GitHubDesktop-linux-${arch}-3.4.3-linux1.deb
-        echo "github desktop installed."
+        if ! command -v github-desktop >/dev/null 2>&1; then
+            sudo wget https://github.com/shiftkey/desktop/releases/download/release-3.4.3-linux1/GitHubDesktop-linux-${arch}-3.4.3-linux1.deb
+            sudo dpkg -i GitHubDesktop-linux-${arch}-3.4.3-linux1.deb || echo "github desktop install failed."
+            sudo rm -f GitHubDesktop-linux-${arch}-3.4.3-linux1.deb
+            echo "github desktop installed."
+        else
+            echo "github desktop already installed."
+        fi
     }
 
     # Cursor をインストールする関数
     install_cursor() {
         appimage="${HOME}/Applications/cursor"
         mkdir -p "${HOME}/Applications"
-
-        if [ "${arch}" = "amd64" ]; then
-            curl -L https://downloader.cursor.sh/inulx -o "${appimage}" || echo "cursor download failed."
-        else
-            curl -L https://github.com/coder/cursor-arm/releases/download/v0.42.2/cursor_0.42.2_linux_arm64.AppImage -o "${appimage}" || echo "cursor download failed."
+        if ! [ -f "${appimage}" ]; then
+            if [ "${arch}" = "amd64" ]; then
+                curl -L https://downloader.cursor.sh/inulx -o "${appimage}" || echo "cursor download failed."
+            else
+                curl -L https://github.com/coder/cursor-arm/releases/download/v0.42.2/cursor_0.42.2_linux_arm64.AppImage -o "${appimage}" || echo "cursor download failed."
+            fi
         fi
-
         sudo chmod a+x "${appimage}"
-        command -v libfuse2 >/dev/null || sudo apt-get install -y libfuse2 || echo "libfuse2 install failed."
+        sudo apt-get install -y libfuse2 || echo "libfuse2 install failed."
         echo "${appimage} installed."
     }
 
     # Wireshark をインストールおよび設定する関数
     install_wireshark() {
-        sudo apt install -y wireshark || echo "wireshark install failed."
-        sudo groupadd -f wireshark
-        sudo usermod -aG wireshark "$USER_NAME"
-        echo "wireshark installed."
+        if ! command -v wireshark >/dev/null 2>&1; then
+            sudo apt install -y wireshark || echo "wireshark install failed."
+            sudo groupadd -f wireshark
+            sudo usermod -aG wireshark "$USER_NAME"
+            echo "wireshark installed."
+        else
+            echo "wireshark already installed."
+        fi
     }
 
     # Ruby と Fusuma をインストールおよび設定する関数
@@ -273,11 +296,15 @@ echo "desktop system setup"
         command -v gem >/dev/null || mise use ruby -y || sudo apt-get install -y ruby || echo "ruby install failed."
         echo "ruby installed."
 
-        sudo gem install fusuma || echo "fusuma install failed."
-        sudo groupadd -f input
-        sudo usermod -aG input "$USER_NAME"
-        fusuma -d
-        echo "fusuma installed."
+        if ! command -v fusuma >/dev/null 2>&1; then
+            sudo gem install fusuma || echo "fusuma install failed."
+            sudo groupadd -f input
+            sudo usermod -aG input "$USER_NAME"
+            fusuma -d
+            echo "fusuma installed."
+        else
+            echo "fusuma already installed."
+        fi
     }
 
     # 日本語環境の設定
@@ -360,6 +387,5 @@ echo "desktop system setup"
 {{ end -}}
 
 echo "--------------------------------"
-
 echo "desktop setup complete"
 echo "--------------------------------"
