gg

diff --git a/run_onchange_bootstrap.sh.tmpl b/run_onchange_bootstrap.sh.tmpl
--- a/run_onchange_bootstrap.sh.tmpl
+++ b/run_onchange_bootstrap.sh.tmpl
@@ -165,11 +165,12 @@ echo "--------------------------------"
         else
             echo "cargo already installed."
         fi
+        . ${HOME}/.cargo/env
         command -v cargo >> ${HOME}/which || echo "cargo not found"
 
         echo "cargo tools install start..."
         if ! command -v cargo-binstall >/dev/null; then
-            cargo install cargo-binstall@1.6.9 || cargo install starship@1.20.1 sheldon fd-find@9.0.0 xh bat || echo "cargo tools install failed."
+            cargo install cargo-binstall@1.6.9 --locked || cargo install starship@1.20.1 sheldon fd-find@9.0.0 xh bat || echo "cargo tools install failed."
         else
             echo "cargo-binstall already installed."
         fi
