ii

diff --git a/run_onchange_bootstrap.sh.tmpl b/run_onchange_bootstrap.sh.tmpl
--- a/run_onchange_bootstrap.sh.tmpl
+++ b/run_onchange_bootstrap.sh.tmpl
@@ -109,6 +109,8 @@ echo "--------------------------------"
         if command -v docker >/dev/null 2>&1; then
             echo "docker already installed."
         else
+            sudo apt-get update -y
+            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release software-properties-common || echo "apt install failed."
             curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o usr/share/keyrings/docker-archive-keyring.gpg
             echo "deb [arch=${arch} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee etc/apt/sources.list.d/docker.list >/dev/null
             sudo apt-get update -y
