nnn

diff --git a/run_once_before_bw_unlock.sh.tmpl b/run_once_before_bw_unlock.sh.tmpl
--- a/run_once_before_bw_unlock.sh.tmpl
+++ b/run_once_before_bw_unlock.sh.tmpl
@@ -1,7 +1,7 @@
 #! /usr/bin/env bash
 
 echo "--------------------------------"
-echo "run_once_before_bitwarden.sh.tmpl"
+echo "run_once_before_bw_unlock.sh.tmpl"
 echo "OS: {{ .chezmoi.os | quote }}"
 echo "before bitwarden cli install"
 cd ${HOME}
@@ -13,6 +13,7 @@ VERSION="20.18.1"
 NPM="${SHIMS}/installs/node/${VERSION}/bin/npm"
 BW="${SHIMS}/installs/node/${VERSION}/bin/bw"
 SESSION="{{ .chezmoi.sourceDir }}/.env"
+MASTER="${MASTER:-}"
 
 # mise なければインストール
 {{ if eq .chezmoi.os "darwin" -}}
@@ -44,16 +45,17 @@ fi
 echo "--------------------------------"
 # bw cli があればロック解除
 if command -v bw >/dev/null 2>&1; then
-    echo "export BW_SESSION="$(bw unlock --raw)"" >> ${SESSION} || echo "bw unlock failed."
+    echo "export BW_SESSION="$(bw unlock ${MASTER} --raw)"" >> ${SESSION} || echo "bw unlock failed."
 
 elif [ -f ${BW} ]; then
-    echo "export BW_SESSION="$(${BW} unlock --raw)"" >> ${SESSION} || echo "bw unlock failed."
+    echo "export BW_SESSION="$(${BW} unlock ${MASTER} --raw)"" >> ${SESSION} || echo "bw unlock failed."
 
 else
     echo "bw cli not found."
 fi
 cat ${SESSION} || echo "${SESSION} not found."
 echo "--------------------------------"
+echo "PATH ..."
 echo "${PATH}" | tr ':' '\n'
 echo "--------------------------------"
 echo "bw install complete"
