www

diff --git a/run_once_before_age_decrypt.sh.tmpl b/run_once_before_age_decrypt.sh.tmpl
--- a/run_once_before_age_decrypt.sh.tmpl
+++ b/run_once_before_age_decrypt.sh.tmpl
@@ -15,14 +15,14 @@ key_path="{{ .chezmoi.sourceDir }}/${key_name}"
 # age なければインストール
 echo "age install..."
 {{ if eq .chezmoi.os "darwin" -}}
-    command -v age >/dev/null || brew install age || echo "age install failed"
+command -v age >/dev/null || brew install age || echo "age install failed"
 
 {{ else if eq .chezmoi.os "linux" -}}
-    command -v age >/dev/null || sudo apt-get install -y age || echo "age install failed"
+command -v age >/dev/null || sudo apt-get install -y age || echo "age install failed"
 
 {{ else -}}
-    echo "Your OS is {{ .chezmoi.os }}"
-    curl -sSL https://github.com/FiloSottile/age/releases/download/v1.1.2/age-v1.1.2-darwin-amd64.tar.gz | tar xz
+echo "Your OS is {{ .chezmoi.os }}"
+curl -sSL https://github.com/FiloSottile/age/releases/download/v1.1.2/age-v1.1.2-darwin-amd64.tar.gz | tar xz
 
 {{ end }}
 command -v age || echo "age command not found"
