op

diff --git a/run_once_before_0_bitwarden.sh.tmpl b/run_once_before_0_bitwarden.sh.tmpl
--- a/run_once_before_0_bitwarden.sh.tmpl
+++ b/run_once_before_0_bitwarden.sh.tmpl
@@ -7,24 +7,24 @@ cd ${HOME}
 {{ if eq .chezmoi.os "darwin" -}}
     brew install mise
     mise use -g node@20.18.1 -y && mise activate bash || echo "node install failed."
-    ${HOME}/.local/share/mise/node/installs/20.18.1/bin/npm install -g @bitwarden/cli || echo "bitwarden cli install failed."
+    ${HOME}/.local/share/mise/installs/node/20.18.1/bin/npm install -g @bitwarden/cli || echo "bitwarden cli install failed."
 
 {{ else if eq .chezmoi.os "linux" -}}
     if ! command -v mise >/dev/null 2>&1; then
         curl https://mise.run | sh
-        ${HOME}/.local/bin/mise use -g bitwarden node@20.18.1 -y && ${HOME}/.local/bin/mise activate bash || echo "mise install failed."
+        ${HOME}/.local/bin/mise use -g bitwarden@2024.11.0 node@20.18.1 -y && ${HOME}/.local/bin/mise activate bash || echo "mise install failed."
     else
-        mise use -g bitwarden node@20.18.1 -y && mise activate bash
+        mise use -g bitwarden@2024.11.0 node@20.18.1 -y && mise activate bash
     fi
 {{ end -}}
 
 if command -v bw >/dev/null 2>&1; then
     echo "export BW_SESSION="$(bw unlock --raw)"" >> .env || echo "bw unlock failed."
 
-elif command -v ${HOME}/.local/share/mise/bitwarden/installs/2024.11.0/bin/bw >/dev/null 2>&1; then
-    echo "export BW_SESSION="$(${HOME}/.local/share/mise/bitwarden/installs/2024.11.0/bin/bw unlock --raw)"" >> .env || echo "bw unlock failed."
+elif command -v ${HOME}/.local/share/mise/installs/bitwarden/2024.11.0/bin/bw >/dev/null 2>&1; then
+    echo "export BW_SESSION="$(${HOME}/.local/share/mise/installs/bitwarden/2024.11.0/bin/bw unlock --raw)"" >> .env || echo "bw unlock failed."
 
-elif command -v ${HOME}/.local/share/mise/node/installs/20.18.1/bin/bw >/dev/null 2>&1; then
+elif command -v ${HOME}/.local/share/mise/installs/node/20.18.1/bin/bw >/dev/null 2>&1; then
     echo "export BW_SESSION="$(${HOME}/.local/share/mise/node/installs/20.18.1/bin/bw unlock --raw)"" >> .env || echo "bw unlock failed."
 
 else
