tmpl

diff --git a/run_onchange_userconf.sh.tmpl b/run_onchange_userconf.sh.tmpl
--- a/run_onchange_userconf.sh.tmpl
+++ b/run_onchange_userconf.sh.tmpl
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 echo "Your git user is ..."
-cat ~/.config/git/userconf
+cat ~/.config/git/user.conf
 
 echo "userconf update ? (y/n)"
 #read ans
@@ -9,4 +9,7 @@ echo "userconf update ? (y/n)"
 #  git config --global user.name "Your Name"
 #  git config --global user.email "your.email@example.com"
 #fi
-echo "done"
+
+echo "Dotfiles link ..." && ln -sf ~/.local/share/chezmoi ~/dotfiles && ls -la ~/dotfiles || echo "Dotfiles link failed!!"
+
+echo "Change settings done!!"
