www

diff --git a/run_once_before_bw_unlock.sh.tmpl b/run_once_before_bw_unlock.sh.tmpl
--- a/run_once_before_bw_unlock.sh.tmpl
+++ b/run_once_before_bw_unlock.sh.tmpl
@@ -14,16 +14,13 @@ NPM="${SHIMS}/installs/node/${VERSION}/bin/npm"
 BW="${SHIMS}/installs/node/${VERSION}/bin/bw"
 SESSION="{{ .chezmoi.sourceDir }}/.env"
 
+# age のパスフレーズが要求される
 # マスターパスワードを復号
 {{ if ne .name "runner" -}}
-    SHHH="$(chezmoi decrypt {{ .chezmoi.sourceDir }}/shhh.txt)"
-    echo "export MASTER=${MASTER:-${SHHH}}" >> ${SESSION}
-    MASTER="${MASTER:-${SHHH}}"
-{{ else -}}
-    echo "export MASTER=${MASTER}" >> ${SESSION}
-    MASTER="${MASTER:-}"
+    MASTER="$(chezmoi decrypt {{ .chezmoi.sourceDir }}/shhh.txt)"
 {{ end -}}
 
+# age のパスフレーズが要求される
 # マスターパスワードを暗号化
 # echo "${MASTER}" | chezmoi encrypt > {{ .chezmoi.sourceDir }}/shhh.txt
 
@@ -39,12 +36,12 @@ SESSION="{{ .chezmoi.sourceDir }}/.env"
         curl https://mise.run | sh
     fi
     ${MISE} use -g node@${VERSION} -y && ${MISE} activate bash >/dev/null || echo "node install failed."
-
 {{ end -}}
 # mise shims のパスを通す
 export PATH="${SHIMS}/shims:${PATH}"
 echo "--------------------------------"
-# npm なければインストール
+
+# npm で bitwarden cli をインストール
 if command -v npm >/dev/null 2>&1; then
     npm install -g @bitwarden/cli || echo "bitwarden cli install failed."
 
@@ -52,16 +49,16 @@ elif [ -f ${NPM} ]; then
     ${NPM} install -g @bitwarden/cli || echo "bitwarden cli install failed."
 
 else
-    echo "bitwarden cli install failed."
+    echo "npm not found."
 fi
 echo "--------------------------------"
 
 # bw cli があればロック解除
 if command -v bw >/dev/null 2>&1; then
-    echo "export BW_SESSION="$(bw unlock ${MASTER} --raw)"" > ${SESSION} || echo "bw unlock failed."
+    echo "export BW_SESSION="$(bw unlock ${MASTER:-} --raw)"" >> ${SESSION} || echo "bw unlock failed."
 
 elif [ -f ${BW} ]; then
-    echo "export BW_SESSION="$(${BW} unlock ${MASTER} --raw)"" > ${SESSION} || echo "bw unlock failed."
+    echo "export BW_SESSION="$(${BW} unlock ${MASTER:-} --raw)"" >> ${SESSION} || echo "bw unlock failed."
 
 else
     echo "bw cli not found."
@@ -69,6 +66,7 @@ else
 fi
 cat ${SESSION} || echo "${SESSION} not found."
 echo "--------------------------------"
+
 echo "PATH ..."
 echo "${PATH}" | tr ':' '\n'
 echo "--------------------------------"
diff --git a/run_onchange_setup.sh.tmpl b/run_onchange_setup.sh.tmpl
--- a/run_onchange_setup.sh.tmpl
+++ b/run_onchange_setup.sh.tmpl
@@ -200,7 +200,7 @@ echo "--------------------------------"
     network_setup() {
         # sudo networksetup -SetAirportPower en0 on
         # sudo networksetup -SetAirportNetwork en0 <SSID> <PASSWORD>
-        sudo networksetup -SetDNSServers Wi-Fi 1.1.1.2 1.0.0.2 192.168.0.1
+        # sudo networksetup -SetDNSServers Wi-Fi 1.1.1.2 1.0.0.2 192.168.0.1
         # sudo networksetup -SetV6Off Wi-Fi
         networksetup -ListNetworkServiceOrder
         nslookup apple.com
@@ -399,6 +399,13 @@ echo "--------------------------------"
         echo "日本語環境の設定が完了しました。"
     }
 
+    # pulseaudio をインストールおよび設定する関数
+    install_pulseaudio() {
+        sudo apt-get install -y pulseaudio libpulse-dev dh-autoreconf dpkg-dev || echo "pulseaudio install failed."
+        echo "pulseaudio installed."
+    }
+
+    # pipewire をインストールおよび設定する関数
     install_pipewire() {
         doko=$(pwd)
         sudo apt-get install -y pipewire pipewire-audio libspa-0.2-dev libpipewire-0.3-dev autoconf libtool || echo "pipewire install failed."
@@ -407,7 +414,8 @@ echo "--------------------------------"
             git clone https://github.com/neutrinolabs/pulseaudio-module-xrdp.git "${HOME}/.config/pipewire/pulseaudio-module-xrdp"
             cd "${HOME}/.config/pipewire/pulseaudio-module-xrdp"
             ./bootstrap
-            ./configure
+            ./configure PULSE_DIR=$(cd ..; pwd)
+            make
             sudo make install
             cd "${doko}"
         fi
