www

diff --git a/run_once_before_bw_unlock.sh.tmpl b/run_once_before_bw_unlock.sh.tmpl
--- a/run_once_before_bw_unlock.sh.tmpl
+++ b/run_once_before_bw_unlock.sh.tmpl
@@ -24,25 +24,39 @@ SESSION="{{ .chezmoi.sourceDir }}/.env"
 # マスターパスワードを暗号化
 # echo "${MASTER}" | chezmoi encrypt > {{ .chezmoi.sourceDir }}/shhh.txt
 
-mise_npm() {
-    # mise なければインストール
+# mise なければインストール
+mise_install() {
 {{ if eq .chezmoi.os "darwin" -}}
     command -v mise >/dev/null || brew install mise
-    mise use -g node@${VERSION} -y && mise activate bash >/dev/null || echo "node install failed."
 
 {{ else if eq .chezmoi.os "linux" -}}
     command -v mise >/dev/null || curl https://mise.run | sh
-    ${MISE} use -g node@${VERSION} -y && ${MISE} activate bash >/dev/null || echo "node install failed."
+    export PATH="${HOME}/.local/bin:${PATH}"
 
 {{ end -}}
 
-    # mise shims のパスを通す
-    export PATH="${SHIMS}/shims:${PATH}"
     echo "--------------------------------"
 }
 
+npm_install() {
+    if ! command -v npm >/dev/null 2>&1; then
+        echo "npm not found."
+
+        if command -v mise >/dev/null 2>&1; then
+            mise use -g node@${VERSION} -y && mise activate bash >/dev/null || echo "node install failed."
+        elif [ -f ${MISE} ]; then
+            ${MISE} use -g node@${VERSION} -y && ${MISE} activate bash >/dev/null || echo "node install failed."
+        else
+            echo "mise not found."
+        fi
+            export PATH="${SHIMS}/shims:${PATH}"
+            export PATH="${SHIMS}/installs/node/${VERSION}/bin:${PATH}"
+    fi
+    echo "node install complete"
+}
+
+# npm で bitwarden cli をインストール
 bw_install() {
-    # npm で bitwarden cli をインストール
     if command -v npm >/dev/null 2>&1; then
         npm install -g @bitwarden/cli || echo "bitwarden cli install failed."
 
@@ -52,6 +66,7 @@ bw_install() {
     else
         echo "npm not found."
     fi
+    export PATH="${SHIMS}/installs/node/${VERSION}/bin:${PATH}"
     echo "--------------------------------"
 }
 
@@ -59,9 +74,11 @@ bw_unlock() {
     MASTER="${MASTER:-}"
     # bw cli があればロック解除
     if command -v bw >/dev/null 2>&1; then
+        bw login {{ .email }} ${MASTER} || echo "bw login failed."
         echo "export BW_SESSION="$(bw unlock ${MASTER} --raw)"" > ${SESSION} || echo "bw unlock failed."
 
     elif [ -f ${BW} ]; then
+        ${BW} login {{ .email }} ${MASTER} || echo "bw login failed."
         echo "export BW_SESSION="$(${BW} unlock ${MASTER} --raw)"" > ${SESSION} || echo "bw unlock failed."
 
     else
@@ -75,7 +92,8 @@ bw_unlock() {
 
 main() {
     echo "bitwarden setup"
-    mise_npm
+    mise_install
+    npm_install
     bw_install
     bw_unlock
     echo "bitwarden setup complete"
diff --git a/run_onchange_bootstrap.sh.tmpl b/run_onchange_bootstrap.sh.tmpl
--- a/run_onchange_bootstrap.sh.tmpl
+++ b/run_onchange_bootstrap.sh.tmpl
@@ -137,13 +137,17 @@ echo "--------------------------------"
         else
             echo "mise already installed."
         fi
+        export PATH="${HOME}/.local/bin:${HOME}/.local/share/mise/shims:$PATH"
+
         command -v mise >> ${HOME}/which || echo "mise not found"
+
         # version 指定しないと arm64 でエラーになる
         mise use -g bun go@1.23.2 -y || echo "mise use failed."
+
         mise activate bash >/dev/null
-        # mise activate --shims
-        export PATH="${HOME}/.local/share/mise/shims:$PATH"
+        mise activate --shims >/dev/null
         echo "mise setup completed."
+
         for cmd in bun go; do
             command -v "$cmd" >> ${HOME}/which || echo "$cmd not found" >> ${HOME}/which
         done
@@ -157,7 +161,7 @@ echo "--------------------------------"
         command -v cargo >> ${HOME}/which || echo "cargo not found"
 
         echo "cargo tools install start..."
-        cargo install cargo-binstall@1.6.9 || echo "cargo-binstall install failed."
+        cargo install cargo-binstall@1.6.9 --locked || echo "cargo-binstall install failed."
         cargo binstall -y starship sheldon fd-find xh bat || echo "cargo tools install failed."
         # cargo binstall starship@1.20.1 sheldon fd-find@9.0.0 xh bat || echo "cargo tools install failed."
         echo "cargo tools installed."
