www

diff --git a/run_once_2_bootstrap.sh.tmpl b/run_once_2_bootstrap.sh.tmpl
--- a/run_once_2_bootstrap.sh.tmpl
+++ b/run_once_2_bootstrap.sh.tmpl
@@ -183,8 +183,10 @@ echo "--------------------------------"
 
     install_act() {
         echo "act install start..."
-        command -v act >/dev/null || curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash || echo "act install failed." >> ${HOME}/which
-        sudo mv ./bin/act ${HOME}/.local/bin && sudo chmod +x ${HOME}/.local/bin/act
+        if ! command -v act >/dev/null; then
+            curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash || echo "act install failed." >> ${HOME}/which
+            sudo mv ./bin/act ${HOME}/.local/bin && sudo chmod +x ${HOME}/.local/bin/act
+        fi
         echo "act installed."
         command -v act >> ${HOME}/which || echo "act not found" >> ${HOME}/which
     }
diff --git a/run_once_before_0_bitwarden.sh.tmpl b/run_once_before_0_bitwarden.sh.tmpl
--- a/run_once_before_0_bitwarden.sh.tmpl
+++ b/run_once_before_0_bitwarden.sh.tmpl
@@ -9,23 +9,23 @@ cd ${HOME}
     mise use -g node@20.18.1 -y && mise activate bash || echo "node install failed."
     ${HOME}/.local/share/mise/installs/node/20.18.1/bin/npm install -g @bitwarden/cli || echo "bitwarden cli install failed."
     export PATH="${HOME}/.local/share/mise/shims:$PATH"
+
 {{ else if eq .chezmoi.os "linux" -}}
     if ! command -v mise >/dev/null 2>&1; then
         curl https://mise.run | sh
-        ${HOME}/.local/bin/mise use -g bitwarden@2024.11.0 node@20.18.1 -y && ${HOME}/.local/bin/mise activate bash || echo "mise install failed."
+        ${HOME}/.local/bin/mise use -g node@20.18.1 -y && ${HOME}/.local/bin/mise activate bash || echo "mise install failed."
+        ${HOME}/.local/share/mise/installs/node/20.18.1/bin/npm install -g @bitwarden/cli || echo "bitwarden cli install failed."
     else
-        mise use -g bitwarden@2024.11.0 node@20.18.1 -y && mise activate bash
+        mise use -g node@20.18.1 -y && mise activate bash
+        ${HOME}/.local/share/mise/installs/node/20.18.1/bin/npm install -g @bitwarden/cli || echo "bitwarden cli install failed."
     fi
+
     export PATH="${HOME}/.local/share/mise/shims:$PATH"
 {{ end -}}
 
 if command -v bw >/dev/null 2>&1; then
     echo "bw cli in PATH"
     echo "export BW_SESSION="$(bw unlock --raw)"" >> .env || echo "bw unlock failed."
-
-elif [ -f ${HOME}/.local/share/mise/installs/bitwarden/2024.11.0/bin/bw ]; then
-    echo "bw cli not in PATH"
-    echo "export BW_SESSION="$(${HOME}/.local/share/mise/installs/bitwarden/2024.11.0/bin/bw unlock --raw)"" >> .env || echo "bw unlock failed."
 
 elif [ -f ${HOME}/.local/share/mise/installs/node/20.18.1/bin/bw ]; then
     echo "bw cli not in PATH"
