l

diff --git a/run_once_bootstrap.sh.tmpl b/run_once_bootstrap.sh.tmpl
--- a/run_once_bootstrap.sh.tmpl
+++ b/run_once_bootstrap.sh.tmpl
@@ -152,7 +152,7 @@ echo "--------------------------------"
 
         echo "cargo tools install start..."
         cargo install cargo-binstall@1.6.9 || echo "cargo-binstall install failed."
-        cargo binstall starship sheldon fd-find xh bat || echo "cargo tools install failed."
+        cargo binstall -y starship sheldon fd-find xh bat || echo "cargo tools install failed."
         # cargo binstall starship@1.20.1 sheldon fd-find@9.0.0 xh bat || echo "cargo tools install failed."
         echo "cargo tools installed."
         for cmd in starship sheldon fd xh bat; do
