on

diff --git a/run_once_before_0_bitwarden.sh.tmpl b/run_once_before_0_bitwarden.sh.tmpl
--- a/run_once_before_0_bitwarden.sh.tmpl
+++ b/run_once_before_0_bitwarden.sh.tmpl
@@ -5,19 +5,20 @@ echo "before bitwarden cli install"
 cd ${HOME}
 
 {{ if eq .chezmoi.os "darwin" -}}
-    brew install bitwarden-cli node@20 || echo "bitwarden cli install failed."
+    brew install mise
+    mise use -g bitwarden node@20.18 -y && mise activate bash || echo "bitwarden cli install failed."
 
 {{ else if eq .chezmoi.os "linux" -}}
     curl https://mise.run | sh
 
     if command -v mise >/dev/null 2>&1; then
-        mise use -g bitwarden node@20 -y && mise activate bash
+        mise use -g bitwarden node@20.18 -y && mise activate bash
 
     elif command -v cargo >/dev/null 2>&1; then
-        cargo install mise && ${HOME}/.cargo/bin/mise use -g bitwarden node@20 -y && ${HOME}/.cargo/bin/mise activate bash
+        cargo install mise && ${HOME}/.cargo/bin/mise use -g bitwarden node@20.18 -y && ${HOME}/.cargo/bin/mise activate bash
 
     else
-        sudo apt-get install -y cargo && cargo install mise && ${HOME}/.cargo/bin/mise use -g bitwarden node@20 -y && ${HOME}/.cargo/bin/mise activate bash
+        sudo apt-get install -y cargo && cargo install mise && ${HOME}/.cargo/bin/mise use -g bitwarden node@20.18 -y && ${HOME}/.cargo/bin/mise activate bash
     fi
 {{ end -}}
 
