brew

diff --git a/run_onchange_bootstrap.sh.tmpl b/run_onchange_bootstrap.sh.tmpl
--- a/run_onchange_bootstrap.sh.tmpl
+++ b/run_onchange_bootstrap.sh.tmpl
@@ -270,17 +270,10 @@ echo "--------------------------------"
 
     # Brewfile を使用してパッケージをインストール
     install_brew_packages() {
-        BREWFILE_PATH="$HOME/.config/Brewfile"
-
-        if [ -f "$BREWFILE_PATH" ]; then
-            echo "Brewfile ($BREWFILE_PATH) install packages."
-            brew tap Homebrew/bundle
-            brew bundle --file="$BREWFILE_PATH" || echo "brew bundle install failed"
-        else
-            echo "specified Brewfile ($BREWFILE_PATH) not found. skip."
-        fi
         brew --version
+        brew tap Homebrew/bundle
         brew install {{ .packages.darwin.brews | join " " }} || echo "brew install failed."
+        brew install {{ .packages.darwin.casks | join " " }} || echo "cask install failed."
         brew update
         brew upgrade
         brew autoremove
