daw

diff --git a/home/.chezmoiscripts/run_onchange_after_vscode.sh.tmpl b/home/.chezmoiscripts/run_onchange_after_vscode.sh.tmpl
--- a/home/.chezmoiscripts/run_onchange_after_vscode.sh.tmpl
+++ b/home/.chezmoiscripts/run_onchange_after_vscode.sh.tmpl
@@ -9,7 +9,7 @@ CODE_DIR="${HOME}/.local/share/Code"
 
 # 環境によって変わる 設定ファイルの場所
 if command -v cursor >/dev/null 2>&1 || [ -f "${HOME}/Applications/cursor" ]; then
-    CODE_DIR="${HOME}/.local/share/Cursor"
+    CODE_DIR="${HOME}/.config/Cursor"
 fi
 # VSCodeのUserディレクトリの作成
 sudo mkdir -p "${CODE_DIR}/User"
@@ -17,20 +17,25 @@ sudo mkdir -p "${CODE_DIR}/User"
 {{ if ne (env "REMOTE_CONTAINERS") "true" -}}
 
 # 現在インストールされている拡張機能のリストを取得
-INSTALLED_EXTENSIONS=$(code --list-extensions | jq -R -s 'split("\n")[:-1]')
+if command -v code >/dev/null 2>&1; then
+    INSTALLED_EXTENSIONS=$(code --list-extensions | jq -R -s 'split("\n")[:-1]')
 
-{{ range .packages.extensions -}}
+    {{ range .packages.extensions -}}
 
-# jqを使用して拡張機能が既にインストールされているかチェック
-if echo "${INSTALLED_EXTENSIONS}" | jq -e 'contains(["{{ . }}"])' > /dev/null; then
-    echo "{{ . }} already installed."
+    # jqを使用して拡張機能が既にインストールされているかチェック
+    if echo "${INSTALLED_EXTENSIONS}" | jq -e 'contains(["{{ . }}"])' > /dev/null; then
+        echo "{{ . }} already installed."
+
+    else
+        echo "Installing {{ . }}..."
+        code --force --install-extension {{ . }} || echo "{{ . }} install failed."
+    fi
+
+    {{ end }}{{/* range .packages.extensions */}}
 
 else
-    echo "Installing {{ . }}..."
-    code --force --install-extension {{ . }} || echo "{{ . }} install failed."
+    echo "code is not installed"
 fi
-
-{{ end }}{{/* range .packages.extensions */}}
 
 {{ end }}{{/* if ne (env "REMOTE_CONTAINERS") "true" */}}
 
@@ -64,13 +69,13 @@ extensions_json() {
     fi
 
     if command -v code >/dev/null 2>&1; then
-        sudo ln -sf "${FROM}/extensions.json" "${CODEX}"
-        echo "new ${CODEX} created."
+        sudo code --list-extensions | xargs -I {} sh -c "jq '.recommendations += [\"{}\"]' ${CODEX} | sudo tee temp > /dev/null && sudo mv temp ${CODEX}"
+        echo '{"recommendations": [],"unwantedRecommendations":[]}' | sudo tee "${CODEX}" > /dev/null
+        echo 'extension update done!'
     else
         # インストールされている拡張機能を"extensions.json"の形式で出力する
-        echo '{"recommendations": [],"unwantedRecommendations":[]}' | sudo tee "${CODEX}" > /dev/null
-        sudo code --list-extensions | xargs -I {} sh -c "jq '.recommendations += [\"{}\"]' ${CODEX} | sudo tee temp > /dev/null && sudo mv temp ${CODEX}"
-        echo 'extension update done!'
+        sudo ln -sf "${FROM}/extensions.json" "${CODEX}"
+        echo "new ${CODEX} created."
     fi
 
     cat "${CODEX}"
