add

diff --git a/home/.chezmoiscripts/run_once_before_age.sh.tmpl b/home/.chezmoiscripts/run_once_before_age.sh.tmpl
--- a/home/.chezmoiscripts/run_once_before_age.sh.tmpl
+++ b/home/.chezmoiscripts/run_once_before_age.sh.tmpl
@@ -5,21 +5,24 @@ echo "--------------------------------"
 
 if command -v age >/dev/null; then
     echo "age already installed"
+
+elif command -v mise >/dev/null; then
+    mise use -g age@latest -y || echo "age install failed"
+
+elif command -v brew >/dev/null; then
+    brew install age || echo "age install failed"
+
+elif command -v apt-get >/dev/null; then
+    sudo apt-get install -y age || echo "age install failed"
+
+elif command -v curl >/dev/null; then
+    curl -sSL https://github.com/FiloSottile/age/releases/download/v1.1.2/age-v1.1.2-linux-$(dpkg --print-architecture).tar.gz | tar xz || echo "age install failed"
+
 else
-    if command -v brew >/dev/null; then
-        brew install age || echo "age install failed"
-
-    elif command -v apt-get >/dev/null; then
-        sudo apt-get install -y age || echo "age install failed"
-
-    elif command -v curl >/dev/null; then
-        curl -sSL https://github.com/FiloSottile/age/releases/download/v1.1.2/age-v1.1.2-linux-$(dpkg --print-architecture).tar.gz | tar xz || echo "age install failed"
-
-    else
-        echo "age not installed"
-        exit 1
-    fi
+    echo "age not installed"
+    exit 1
 fi
+
 age --version || echo "age command not found && exit 1"
 echo "--------------------------------"
 
@@ -27,12 +30,12 @@ echo "--------------------------------"
 # key.txt をパスフレーズで復号するので事前に用意
 # https://www.chezmoi.io/user-guide/frequently-asked-questions/encryption/
 
-{{ if ne .age false -}}
+{{ if ne .age false }}
 
 {{/* .chezmoi.toml.tmpl と合わせる */}}
 identity="${HOME}/.config/chezmoi/key.txt"
 
-{{- /* age-keygen | age --armor --passphrase ${key_name} で生成したキーのファイル名 */ -}}
+{{/* age-keygen | age --armor --passphrase ${key_name} で生成したキーのファイル名 */}}
 key_name="key.txt.age"
 key_path="{{ .chezmoi.sourceDir }}/${key_name}"
 
@@ -51,4 +54,4 @@ fi
 echo "Decrypt-private-key complete."
 echo "--------------------------------"
 
-{{- end -}}
+{{ end }}
diff --git a/home/.chezmoiscripts/run_once_before_bw.sh.tmpl b/home/.chezmoiscripts/run_once_before_bw.sh.tmpl
--- a/home/.chezmoiscripts/run_once_before_bw.sh.tmpl
+++ b/home/.chezmoiscripts/run_once_before_bw.sh.tmpl
@@ -18,7 +18,7 @@ echo "--------------------------------"
 
 MISE="${HOME}/.local/bin/mise"
 SHIMS="${HOME}/.local/share/mise"
-VERSION="20.19.1"
+VERSION="20"
 NPM="${SHIMS}/installs/node/${VERSION}/bin/npm"
 BW="${SHIMS}/installs/node/${VERSION}/bin/bw"
 SESSION="{{ .chezmoi.sourceDir }}/.env"
@@ -28,24 +28,20 @@ mise_install() {
     if command -v mise >/dev/null 2>&1; then
         echo "mise already installed."
 
-    else
-        echo "mise not found."
+    elif command -v brew >/dev/null 2>&1; then
+        brew install mise || echo "mise install failed."
 
-        if command -v brew >/dev/null 2>&1; then
-            brew install mise || echo "mise install failed."
-
-        elif command -v curl >/dev/null 2>&1; then
-            curl https://mise.run | sh || echo "mise install failed."
-
-        else
-            echo "mise install failed."
-            exit 1
-
-        fi
+    elif command -v curl >/dev/null 2>&1; then
+        curl https://mise.run | sh || echo "mise install failed."
         export PATH="${HOME}/.local/bin:${PATH}"
-        mise --version || echo "mise command not found."
-        echo "mise installed"
+
+    else
+        echo "mise install failed."
+        exit 1
     fi
+
+    mise --version || echo "mise command not found."
+    echo "mise installed"
     echo "--------------------------------"
 }
 
@@ -54,25 +50,22 @@ node_install() {
     if command -v npm >/dev/null 2>&1; then
         echo "npm already installed."
 
+    elif command -v mise >/dev/null 2>&1; then
+        mise use -g node@${VERSION} -y && mise activate bash >/dev/null || echo "node install failed."
+
+    elif [ -f ${MISE} ]; then
+        ${MISE} use -g node@${VERSION} -y && ${MISE} activate bash >/dev/null || echo "node install failed."
+
     else
-        echo "npm not found."
+        echo "mise not found."
+        exit 1
 
-        if command -v mise >/dev/null 2>&1; then
-            mise use -g node@${VERSION} -y && mise activate bash >/dev/null || echo "node install failed."
-
-        elif [ -f ${MISE} ]; then
-            ${MISE} use -g node@${VERSION} -y && ${MISE} activate bash >/dev/null || echo "node install failed."
-
-        else
-            echo "mise not found."
-            exit 1
-
-        fi
-        export PATH="${SHIMS}/shims:${PATH}"
-        export PATH="${SHIMS}/installs/node/${VERSION}/bin:${PATH}"
-        npm --version || echo "npm command not found."
-        echo "node installed"
     fi
+
+    export PATH="${SHIMS}/shims:${PATH}"
+    export PATH="${SHIMS}/installs/node/${VERSION}/bin:${PATH}"
+    npm --version || echo "npm command not found."
+    echo "node installed"
     echo "--------------------------------"
 }
 
@@ -81,26 +74,21 @@ bw_install() {
     if command -v bw >/dev/null 2>&1; then
         echo "bw already installed."
 
+    elif command -v npm >/dev/null 2>&1; then
+        npm install -g @bitwarden/cli || echo "bitwarden cli install failed."
+
+    elif [ -f ${NPM} ]; then
+        ${NPM} install -g @bitwarden/cli || echo "bitwarden cli install failed."
+
     else
-        echo "bw not found."
-
-        if command -v npm >/dev/null 2>&1; then
-            npm install -g @bitwarden/cli || echo "bitwarden cli install failed."
-
-        elif [ -f ${NPM} ]; then
-            ${NPM} install -g @bitwarden/cli || echo "bitwarden cli install failed."
-
-        else
-            echo "npm not found."
-            # sudo snap install bw
-            # exit 1
-
-        fi
-        export PATH="${SHIMS}/installs/node/${VERSION}/bin:${PATH}"
-        bw --version || echo "bw command not found."
-        echo "Bitwarden CLI installed."
+        echo "npm not found."
+        # sudo snap install bw
+        #exit 1
 
     fi
+    export PATH="${SHIMS}/installs/node/${VERSION}/bin:${PATH}"
+    bw --version || echo "bw command not found."
+    echo "Bitwarden CLI installed."
     echo "--------------------------------"
 }
 
@@ -121,10 +109,8 @@ bw_unlock() {
     # .env 表示
     if [ -f ${SESSION} ]; then
         cat ${SESSION}
-
     else
         echo "export BW_SESSION=${BW_SESSION:-}" > ${SESSION} && cat ${SESSION}
-
     fi
     echo "--------------------------------"
 }
