ddd

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,11 +1,18 @@
 FROM ubuntu:24.04
 
+# パッケージのインストールを非対話形式で行う
 ENV DEBIAN_FRONTEND=noninteractive
+# dockerコンテナ内で実行されていることを示す
 ENV DOCKER=true
 
+# パッケージを更新
 RUN apt-get -y update
 RUN apt-get -y upgrade
 
+# タイムゾーンを設定
+# ロケールを設定
+# fcitx5を設定
+# 日本語入力を設定
 RUN apt-get install -y \
     language-pack-ja \
     language-pack-ja-base \
@@ -24,33 +31,40 @@ RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezo
     locale-gen ja_JP.UTF-8 && \
     echo LANGUAGE=${LANGUAGE} >> /etc/default/locale && \
     echo LANG=${LANG} >> /etc/default/locale && \
-    echo LC_ALL=${LC_ALL} >> /etc/default/locale
+    echo LC_ALL=${LC_ALL} >> /etc/default/locale && \
+    im-config -n fcitx5
 
+# xfce4をインストール
 RUN apt-get install -y \
     xfce4 \
     xfce4-goodies \
     xfce4-session \
-    xfce4-clipman-plugin \
-    tigervnc-standalone-server \
+    xfce4-clipman-plugin
+
+# xrdpをインストール
+RUN apt-get install -y \
     xrdp \
     xorgxrdp \
-    dbus-x11 \
-    gzip \
-    xdotool \
-    xsel \
-    openssh-server \
-    ufw \
-    sudo \
-    systemd
+    tigervnc-standalone-server \
+    dbus-x11
+# xrdp用の不要なパッケージを削除
+RUN apt-get remove -y light-locker xscreensaver
 
+# 必須パッケージをインストール
 RUN apt-get install -y \
+    systemd \
+    sudo \
     zsh \
     make \
     curl \
     git \
     gh \
+    gzip \
     age \
+    gnupg \
     wget \
+    xsel \
+    xdotool \
     vim \
     tree \
     jq \
@@ -64,12 +78,17 @@ RUN apt-get install -y \
     ncmpcpp \
     neofetch \
     mkcert \
+    ufw \
+    openssh-server \
+    avahi-daemon
+
+# 開発用パッケージをインストール 言語のビルドに必要なパッケージ
+RUN apt-get install -y \
     g++ \
     cmake \
     build-essential \
     libssl-dev \
     pkg-config \
-    avahi-daemon \
     libfreetype6-dev \
     libfontconfig1-dev \
     libxcb-xfixes0-dev \
@@ -79,32 +98,38 @@ RUN apt-get install -y \
     software-properties-common \
     python3 \
     ruby \
-    cargo \
     flatpak
 
-RUN apt-get remove -y light-locker xscreensaver && \
-    apt-get autoremove -y && \
-    apt-get clean && \
-    rm -rf /var/cache/apt /var/lib/apt/lists/*
+# 不要なパッケージ キャッシュを削除
+RUN apt-get autoremove -y
+RUN apt-get clean
+RUN rm -rf /var/cache/apt /var/lib/apt/lists/*
 
+# xrdp用の設定
 RUN mkdir -p /var/run/dbus && \
     cp /etc/X11/xrdp/xorg.conf /etc/X11 && \
     sed -i "s/console/anybody/g" /etc/X11/Xwrapper.config && \
     sed -i "s/xrdp\/xorg/xorg/g" /etc/xrdp/sesman.ini && \
     echo "xfce4-session" >> /etc/skel/.Xsession
 
+# ユーザーを作成 デフォルトはubuntu
 # ARG USER=budybye
 # ARG UID=1010
 # ARG GID=$UID
 ARG USER=ubuntu
 ARG HOME=/home/$USER
 
+# デフォルトのシェルをzshに変更
+# パスワードはubuntu
+# sudoのパスワードはなし
+# ホームディレクトリを作成
 RUN chsh -s /usr/bin/zsh && \
     echo "$USER:$USER" | chpasswd && \
     echo "ALL ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
     mkdir -p $HOME && \
     chown -R $USER:$USER $HOME
 
+# devcontainer用ユーザーを作成
 ARG DEV=dev
 ARG DEV_UID=1234
 ARG DEV_GID=$DEV_UID
@@ -116,35 +141,54 @@ RUN groupadd -g $DEV_GID -f $DEV && \
     mkdir -p $DEV_HOME && \
     chown -R $DEV:$DEV $DEV_HOME
 
+# デフォルトユーザーとホームをワークディレクトリに設定
+# ここからsudoを使えるようになる
 USER $USER
 WORKDIR $HOME
 
+# chezmoiをインストール
 RUN sudo sh -c "$(curl -fsSL get.chezmoi.io)" -- -b /usr/local/bin
-
+# dotfilesをクローン
 RUN git clone https://github.com/budybye/dotfiles.git ${HOME}/dotfiles
 
+# miseをインストール
+# miseでnodeをインストール
+# npmでbwをインストール
+# パスを環境変数に追加
 RUN curl https://mise.run | sh && \
     export PATH=${HOME}/.local/bin:${PATH} && \
     mise use -g node@20.18.1 && \
     export PATH=${HOME}/.local/share/mise/shims:${PATH} && \
     export PATH=${HOME}/.local/share/mise/installs/node/20.18.1/bin:${PATH} && \
     npm i -g @bitwarden/cli && \
-    bw --version || echo "bw command not found"
+    bw --version || echo "bw command not found" && \
+    echo "export PATH=${PATH}" >> ${HOME}/.zshenv
 
-EXPOSE 3389
+RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
+    . ${HOME}/.cargo/env && \
+    cargo install cargo-binstall@1.6.9 --locked && \
+    cargo binstall -y starship sheldon fd-find xh bat && \
+    echo 'export PATH=${HOME}/.cargo/bin:${PATH}' >> ${HOME}/.zshenv
 
-RUN im-config -n fcitx5 && \
-    groupadd -f xrdp && \
+# Xrdp用のグループを作成 xsessionをxfce4-sessionに設定
+RUN groupadd -f xrdp && \
     groupadd -f ssl-cert && \
     groupadd -f input && \
     groupadd -f audio && \
     sudo usermod -aG input,xrdp,audio,ssl-cert $USER && \
     echo "xfce4-session" > ~/.xsession && \
-    echo "dbus-launch --exit-with-session usr/bin/xfce4-session" > ~/.startwm.sh && \
+    echo "dbus-launch --exit-with-session /usr/bin/xfce4-session" > ~/.startwm.sh && \
     chmod 755 ~/.startwm.sh && \
     sudo update-alternatives --set x-session-manager /usr/bin/xfce4-session
 
-COPY ./entrypoint.sh /usr/local/bin/entrypoint.sh
-RUN sudo chmod +x /usr/local/bin/entrypoint.sh
-ENTRYPOINT ["entrypoint.sh"]
-CMD ["/bin/bash"]
+# xrdpのポートを公開
+EXPOSE 3389
+
+# コンテナ起動時に実行するスクリプトを設定 /sbin/initを実行してる
+COPY ./entrypoint.sh /usr/local/bin/entrypoint
+RUN sudo chmod +x /usr/local/bin/entrypoint
+ENTRYPOINT ["entrypoint"]
+# エントリーポイントの最後に渡す引数コマンド
+# CMD ["/sbin/init"]
+CMD ["/usr/bin/zsh", "--login"]
+# /usr/bin/zsh を実行してるのでコンテナが起動し続ける
diff --git a/run_onchange_bootstrap.sh.tmpl b/run_onchange_bootstrap.sh.tmpl
--- a/run_onchange_bootstrap.sh.tmpl
+++ b/run_onchange_bootstrap.sh.tmpl
@@ -157,14 +157,22 @@ echo "--------------------------------"
     # Cargo および Rust 関連ツールをインストールする関数
     install_cargo_tools() {
         echo "cargo install start..."
-        command -v cargo >/dev/null || mise use rust -y || sudo apt-get install -y cargo || echo "cargo install failed."
-        echo "cargo installed."
+        if ! command -v cargo >/dev/null; then
+            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y || mise use rust -y || sudo apt-get install -y cargo || echo "cargo install failed."
+            echo "cargo installed."
+        else
+            echo "cargo already installed."
+        fi
         command -v cargo >> ${HOME}/which || echo "cargo not found"
 
         echo "cargo tools install start..."
-        cargo install cargo-binstall@1.6.9 --locked || echo "cargo-binstall install failed."
+        if ! command -v cargo-binstall >/dev/null; then
+            cargo install cargo-binstall@1.6.9 --locked || cargo install starship@1.20.1 sheldon fd-find@9.0.0 xh bat || echo "cargo tools install failed."
+        else
+            echo "cargo-binstall already installed."
+        fi
         cargo binstall -y starship sheldon fd-find xh bat || echo "cargo tools install failed."
-        # cargo binstall starship@1.20.1 sheldon fd-find@9.0.0 xh bat || echo "cargo tools install failed."
+
         echo "cargo tools installed."
         for cmd in starship sheldon fd xh bat; do
             command -v "$cmd" >> ${HOME}/which || echo "$cmd not found"
@@ -183,19 +191,29 @@ echo "--------------------------------"
         command -v go >/dev/null || mise use -g go@1.23.2 -y || sudo apt-get install -y golang || echo "go install failed."
         command -v go >> ${HOME}/which || echo "go not found" >> ${HOME}/which
 
-        ${HOME}/.local/share/mise/shims/go install github.com/aquaproj/aqua/v2/cmd/aqua@latest || echo "aqua install failed."
-        echo "aqua installed."
-        # パスが通っていないので直接パスを指定
-        export PATH="${HOME}/.local/share/mise/installs/go/1.23.2/bin:${PATH}"
+        if ! command -v aqua >/dev/null; then
+            ${HOME}/.local/share/mise/shims/go install github.com/aquaproj/aqua/v2/cmd/aqua@latest || echo "aqua install failed."
+            echo "aqua installed."
+
+            # パスが通っていないので直接パスを指定
+            export PATH="${HOME}/.local/share/mise/installs/go/1.23.2/bin:${PATH}"
+            echo "aqua installed."
+        else
+            echo "aqua already installed."
+        fi
         command -v aqua >> ${HOME}/which || echo "aqua not found" >> ${HOME}/which
     }
 
     # mkcert をインストールおよび設定する関数
     install_mkcert() {
         echo "mkcert install start..."
-        command -v mkcert >/dev/null || mise use mkcert -y || sudo apt install -y mkcert || echo "mkcert install failed."
-        mkcert -install
-        echo "mkcert installed."
+        if ! command -v mkcert >/dev/null; then
+            mise use mkcert -y || sudo apt install -y mkcert || echo "mkcert install failed."
+            mkcert -install
+            echo "mkcert installed."
+        else
+            echo "mkcert already installed."
+        fi
         command -v mkcert >> ${HOME}/which || echo "mkcert not found"
     }
 
@@ -205,8 +223,10 @@ echo "--------------------------------"
             curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash || echo "act install failed."
             sudo chmod +x ./bin/act
             sudo mv -f ./bin/act ${HOME}/.local/bin
+            echo "act installed."
+        else
+            echo "act already installed."
         fi
-        echo "act installed."
         command -v act >> ${HOME}/which || echo "act not found"
     }
 
