ops

diff --git a/home/.chezmoiscripts/linux/run_once_after_docker.sh.tmpl b/home/.chezmoiscripts/linux/run_once_after_docker.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_once_after_docker.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_once_after_docker.sh.tmpl
@@ -3,25 +3,31 @@
 echo "run_once_after_docker.sh.tmpl"
 echo "--------------------------------"
 
+if $(whoami) != "root"; then
+    sudo="sudo"
+else
+    sudo=""
+fi
+
 install_docker() {
     if command -v docker >/dev/null 2>&1; then
         docker --version >> ${HOME}/which
     else
-        sudo apt-get update -y
-        sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release software-properties-common || echo "apt install failed."
-        sudo mkdir -p /etc/apt/keyrings
-        sudo install -m 0755 -d /etc/apt/keyrings
-        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.asc
-        sudo chmod a+r /etc/apt/keyrings/docker.asc
-        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
-        sudo apt-get update -y
-        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin || echo "docker install failed."
+        $sudo apt-get update -y
+        $sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release software-properties-common || echo "apt install failed."
+        $sudo mkdir -p /etc/apt/keyrings
+        $sudo install -m 0755 -d /etc/apt/keyrings
+        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | $sudo gpg --dearmor -o /etc/apt/keyrings/docker.asc
+        $sudo chmod a+r /etc/apt/keyrings/docker.asc
+        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | $sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
+        $sudo apt-get update -y
+        $sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin || echo "docker install failed."
         if [ -f /var/run/docker.sock ]; then
-            sudo chmod 666 /var/run/docker.sock
+            $sudo chmod 666 /var/run/docker.sock
         fi
-        sudo groupadd -f docker
-        sudo usermod -aG docker "$(whoami)"
-        sudo systemctl enable docker
+        $sudo groupadd -f docker
+        $sudo usermod -aG docker "$(whoami)"
+        $sudo systemctl enable docker
         docker info
         docker --version >> ${HOME}/which || echo "docker not found" >> ${HOME}/which
     fi
@@ -36,8 +42,8 @@ install_docker_compose() {
         # ダウンロード URL の作成
         COMPOSE_URL="https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)"
         # Docker Compose のバイナリをダウンロード
-        sudo curl -L "$COMPOSE_URL" -o /usr/local/bin/docker-compose || echo "docker-compose download failed."
-        sudo chmod +x /usr/local/bin/docker-compose
+        $sudo curl -L "$COMPOSE_URL" -o /usr/local/bin/docker-compose || echo "docker-compose download failed."
+        $sudo chmod +x /usr/local/bin/docker-compose
         docker-compose --version >> ${HOME}/which || echo "docker-compose not found" >> ${HOME}/which
     fi
 }
@@ -47,9 +53,9 @@ install_act() {
     if command -v act >/dev/null; then
         echo "act already installed."
     elif command -v curl >/dev/null; then
-        curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash || echo "act install failed."
-        sudo chmod +x ./bin/act
-        sudo mv -f ./bin/act ${HOME}/.local/bin
+        curl https://raw.githubusercontent.com/nektos/act/master/install.sh | $sudo bash || echo "act install failed."
+        $sudo chmod +x ./bin/act
+        $sudo mv -f ./bin/act ${HOME}/.local/bin
         echo "act installed."
     else
         echo "act install failed."
diff --git a/home/.chezmoiscripts/linux/run_once_after_setup.sh.tmpl b/home/.chezmoiscripts/linux/run_once_after_setup.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_once_after_setup.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_once_after_setup.sh.tmpl
@@ -3,43 +3,49 @@
 echo "run_once_after_setup.sh.tmpl"
 echo "--------------------------------"
 
+if $(whoami) != "root"; then
+    sudo="sudo"
+else
+    sudo=""
+fi
+
 japan_setup() {
     echo "japan setup start..."
-    #sudo localectl set-locale LANG=ja_JP.UTF-8
-    #sudo localectl set-locale LANGUAGE=ja_JP:ja
-    #sudo localectl set-x11-keymap jp
-    #sudo localectl set-keymap jp106
-    #sudo timedatectl set-timezone Asia/Tokyo
-    LANG=C xdg-user-dirs-update --force
+    #$sudo localectl set-locale LANG=ja_JP.UTF-8
+    #$sudo localectl set-locale LANGUAGE=ja_JP:ja
+    #$sudo localectl set-x11-keymap jp
+    #$sudo localectl set-keymap jp106
+    #$sudo timedatectl set-timezone Asia/Tokyo
+    #LANG=C xdg-user-dirs-update --force
     # 入力メソッドとしてfcitx5を設定
-    im-config -n fcitx5
+    $sudo im-config -n fcitx5
     echo "japan setup completed."
 }
 
 xrdp_setup() {
     echo "xrdp setup start..."
-    sudo groupadd -f ssl-cert
-    sudo groupadd -f xrdp
+    $sudo groupadd -f ssl-cert
+    $sudo groupadd -f xrdp
     # ubuntuユーザーを必要なグループに追加
-    sudo usermod -aG ssl-cert,xrdp "$(whoami)"
+    $sudo usermod -aG ssl-cert,xrdp "$(whoami)"
     # サービスの再起動
-    sudo systemctl daemon-reload
-    sudo systemctl restart rsyslog
+    $sudo systemctl daemon-reload
+    $sudo systemctl restart rsyslog
     # ファイアウォールで3389番ポート（RDP）を許可
-    sudo ufw allow 3389
+    $sudo ufw allow 3389
     # xrdpサービスを有効化
-    sudo systemctl enable xrdp
+    $sudo systemctl enable xrdp
     # デフォルトのセッションマネージャーをxfce4-sessionに設定
-    sudo update-alternatives --set x-session-manager /usr/bin/xfce4-session
+    $sudo update-alternatives --set x-session-manager /usr/bin/xfce4-session
     # xrdpサービスを起動
-    sudo systemctl start xrdp
+    $sudo systemctl start xrdp
     echo "xrdp setup completed."
 
     echo "以下のコマンドを実行してパスワードを更新してください"
     echo "sudo passwd $(whoami)"
     # ログイン後、ubuntuユーザーのパスワードを再設定を推奨
     # パスワードを再設定しないとログインできない
-    # echo "$(whoami):$(whoami)" | sudo chpasswd
+    # echo "$(whoami):$(whoami)" | $sudo chpasswd
 }
 
 pipewire_setup() {
@@ -47,10 +53,10 @@ pipewire_setup() {
     pipewire_dir="${HOME}/.config/pipewire/pulseaudio-module-xrdp"
 
     # pulseaudio をインストール
-    sudo apt-get install -y pulseaudio libpulse-dev dh-autoreconf dpkg-dev && echo "pulseaudio installed." || echo "pulseaudio install failed."
+    $sudo apt-get install -y pulseaudio libpulse-dev dh-autoreconf dpkg-dev && echo "pulseaudio installed." || echo "pulseaudio install failed."
 
     # pipewire をインストール
-    sudo apt-get install -y pipewire pipewire-audio libspa-0.2-dev libpipewire-0.3-dev autoconf libtool && echo "pipewire installed." || echo "pipewire install failed."
+    $sudo apt-get install -y pipewire pipewire-audio libspa-0.2-dev libpipewire-0.3-dev autoconf libtool && echo "pipewire installed." || echo "pipewire install failed."
     mkdir -p "${HOME}/.config/pipewire"
 
     if [ ! -d "${pipewire_dir}" ]; then
@@ -58,8 +64,9 @@ pipewire_setup() {
         cd "${pipewire_dir}"
         ./bootstrap
         ./configure PULSE_DIR=$(cd ..; pwd)
-        make
-        sudo make install
+        # make
+        # $sudo make install
+        make install
         cd "${doko}"
     fi
     echo "pipewire installed."
diff --git a/home/.chezmoiscripts/linux/run_onchange_after_cli.sh.tmpl b/home/.chezmoiscripts/linux/run_onchange_after_cli.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_onchange_after_cli.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_onchange_after_cli.sh.tmpl
@@ -3,24 +3,30 @@
 echo "run_onchange_after_cli.sh.tmpl"
 echo "--------------------------------"
 
+if $(whoami) != "root"; then
+    sudo="sudo"
+else
+    sudo=""
+fi
+
 # Zsh をデフォルトシェルに変更する関数
 change_shell_to_zsh() {
     # zsh がインストールされているか確認
     if command -v zsh >/dev/null; then
         echo "zsh already installed."
     else
-        sudo apt-get install -y zsh || echo "zsh install failed." >> ${HOME}/which
+        $sudo apt-get install -y zsh || echo "zsh install failed." >> ${HOME}/which
     fi
 
     zsh_path=$(command -v zsh)
     if [ "${SHELL}" != "${zsh_path}" ]; then
         # デフォルトシェルを変更
-        sudo chsh -s "${zsh_path}" "$(whoami)" || echo "zsh default shell change failed."
+        $sudo chsh -s "${zsh_path}" "$(whoami)" || echo "zsh default shell change failed."
     fi
 
     # シンボリックリンクを作成
     if [ ! -f /bin/zsh ] && [ -f /usr/bin/zsh ]; then
-        sudo ln -sf /usr/bin/zsh /bin/zsh
+        $sudo ln -sf /usr/bin/zsh /bin/zsh
     fi
 
     echo "Your shell is ${SHELL}"
@@ -29,25 +35,25 @@ change_shell_to_zsh() {
 }
 
 install_packages() {
-    sudo dpkg --configure -a
+    $sudo dpkg --configure -a
     apt --version
-    sudo apt-get update -y
-    sudo apt-get upgrade -y
+    $sudo apt-get update -y
+    $sudo apt-get upgrade -y
 
     {{ range .packages.linux.cli -}}
 
     if ! dpkg -l | grep -q {{ . }}; then
-        sudo apt-get install -y {{ . }} && echo "{{ . }} installed." || echo "{{ . }} install failed." >> ${HOME}/which
+        $sudo apt-get install -y {{ . }} && echo "{{ . }} installed." || echo "{{ . }} install failed." >> ${HOME}/which
     else
         echo "{{ . }} already installed."
     fi
 
     {{ end }}
 
-    sudo apt-get autoremove -y
-    sudo apt-get autoclean -y
-    sudo rm -rf /var/cache/apt /var/lib/apt/lists/*
-    sudo apt-get check
+    $sudo apt-get autoremove -y
+    $sudo apt-get autoclean -y
+    $sudo rm -rf /var/cache/apt /var/lib/apt/lists/*
+    $sudo apt-get check
     echo "apt install completed."
 }
 
@@ -56,15 +62,15 @@ install_mise() {
         echo "mise already installed."
 
     elif command -v curl >/dev/null 2>&1; then
-            echo "mise install start..."
-            curl https://mise.run | sh || echo "mise install failed."
+        echo "mise install start..."
+        curl https://mise.run | sh || echo "mise install failed."
     else
         echo "curl not found"
-        sudo install -dm 755 /etc/apt/keyrings
-        wget -qO - https://mise.jdx.dev/gpg-key.pub | gpg --dearmor | sudo tee /etc/apt/keyrings/mise-archive-keyring.gpg 1>/dev/null
-        echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=${dpkg --print-architecture}] https://mise.jdx.dev/deb stable main" | sudo tee /etc/apt/sources.list.d/mise.list
-        sudo apt-get update -y
-        sudo apt-get install -y mise || echo "mise install failed."
+        $sudo install -dm 755 /etc/apt/keyrings
+        wget -qO - https://mise.jdx.dev/gpg-key.pub | $sudo gpg --dearmor | $sudo tee /etc/apt/keyrings/mise-archive-keyring.gpg 1>/dev/null
+        echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=${dpkg --print-architecture}] https://mise.jdx.dev/deb stable main" | $sudo tee /etc/apt/sources.list.d/mise.list
+        $sudo apt-get update -y
+        $sudo apt-get install -y mise || echo "mise install failed."
     fi
     export PATH="${HOME}/.local/bin:${HOME}/.local/share/mise/shims:$PATH"
     mise --version >> ${HOME}/which || echo "mise not found" >> ${HOME}/which
@@ -96,7 +102,7 @@ install_cargo_tools() {
 
         else
             echo "curl not found"
-            sudo apt-get install -y cargo || echo "cargo install failed."
+            $sudo apt-get install -y cargo || echo "cargo install failed."
 
         fi
         . ${HOME}/.cargo/env
@@ -133,8 +139,8 @@ install_flatpak() {
     if command -v flatpak >/dev/null; then
         echo "flatpak already installed."
     else
-        sudo apt-get install -y flatpak || echo "flatpak install failed."
-        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
+        $sudo apt-get install -y flatpak || echo "flatpak install failed."
+        $sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
         echo "flatpak installed."
     fi
     flatpak --version >> ${HOME}/which || echo "flatpak not found" >> ${HOME}/which
@@ -148,7 +154,7 @@ install_go_aqua() {
         mise use -g -y go@1.23.2
 
     else
-        sudo apt-get install -y golang || echo "go install failed."
+        $sudo apt-get install -y golang || echo "go install failed."
 
     fi
     go version >> ${HOME}/which || echo "go not found" >> ${HOME}/which
@@ -182,7 +188,7 @@ install_mkcert() {
         mise use -g mkcert -y || echo "mkcert install failed."
 
     else
-        sudo apt install -y mkcert || echo "mkcert install failed."
+        $sudo apt install -y mkcert || echo "mkcert install failed."
     fi
 
     mkcert -install
diff --git a/home/.chezmoiscripts/linux/run_onchange_after_gui.sh.tmpl b/home/.chezmoiscripts/linux/run_onchange_after_gui.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_onchange_after_gui.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_onchange_after_gui.sh.tmpl
@@ -7,24 +7,30 @@ echo "--------------------------------"
 # アーキテクチャを取得
 arch="$(dpkg --print-architecture)"
 
+if $(whoami) != "root"; then
+    sudo="sudo"
+else
+    sudo=""
+fi
+
 # デスクトップ環境のインストール
 # package は .chezmoidata/packages.yaml に記載
 # .packages.linux.gui にはxfceデスクトップ環境をインストールするパッケージを記載
 
 desktop_setup() {
-    sudo apt-get update -y
-    sudo apt-get upgrade -y
+    $sudo apt-get update -y
+    $sudo apt-get upgrade -y
 
     {{ range .packages.linux.gui -}}
     if ! dpkg -l | grep -q {{ . }}; then
-        sudo apt-get install -y {{ . }} || echo "{{ . }} install failed." >> ${HOME}/which
+        $sudo apt-get install -y {{ . }} || echo "{{ . }} install failed." >> ${HOME}/which
     fi
     {{ end }}
 
-    #sudo apt-get remove -y light-locker xscreensaver &&
-    sudo apt-get autoremove -y
-    sudo apt-get clean
-    sudo rm -rf /var/cache/apt /var/lib/apt/lists/*
+    #$sudo apt-get remove -y light-locker xscreensaver &&
+    $sudo apt-get autoremove -y
+    $sudo apt-get clean
+    $sudo rm -rf /var/cache/apt /var/lib/apt/lists/*
     echo "desktop packages installed."
 }
 
@@ -32,10 +38,10 @@ install_brave_browser() {
     if command -v brave-browser >/dev/null 2>&1; then
         echo "brave browser already installed."
     else
-        sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
-        echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
-        sudo apt-get update -y
-        sudo apt-get install -y brave-browser || echo "brave browser install failed."
+        $sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
+        echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | $sudo tee /etc/apt/sources.list.d/brave-browser-release.list
+        $sudo apt-get update -y
+        $sudo apt-get install -y brave-browser || echo "brave browser install failed."
         echo "brave browser installed."
     fi
 }
@@ -44,10 +50,10 @@ install_cloudflare_warp() {
     if command -v warp-cli >/dev/null 2>&1; then
         echo "cloudflare warp already installed."
     else
-        sudo curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
-        echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
-        sudo apt-get update -y
-        sudo apt-get install -y cloudflare-warp || echo "cloudflare warp install failed."
+        $sudo curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | $sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
+        echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | $sudo tee /etc/apt/sources.list.d/cloudflare-client.list
+        $sudo apt-get update -y
+        $sudo apt-get install -y cloudflare-warp || echo "cloudflare warp install failed."
         echo "cloudflare warp installed."
 
         warp-cli --accept-tos registration new
@@ -77,7 +83,7 @@ install_cursor() {
     fi
 
     # cursor の実行ファイルに実行権限を付与
-    sudo chmod a+x "${appimage}"
+    $sudo chmod a+x "${appimage}"
 
     # libfuse2 が必要なのでインストール
     sudo apt-get install -y libfuse2 || echo "libfuse2 install failed."
@@ -92,11 +98,11 @@ install_element_desktop() {
     if command -v element-desktop >/dev/null 2>&1; then
         echo "element desktop already installed."
     else
-        sudo apt-get install -y wget apt-transport-https
-        sudo wget -O /usr/share/keyrings/element-io-archive-keyring.gpg https://packages.element.io/debian/element-io-archive-keyring.gpg
-        echo "deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https://packages.element.io/debian/ default main" | sudo tee /etc/apt/sources.list.d/element-io.list
-        sudo apt-get update -y
-        sudo apt-get install -y element-desktop || echo "element desktop install failed."
+        $sudo apt-get install -y wget apt-transport-https
+        $sudo wget -O /usr/share/keyrings/element-io-archive-keyring.gpg https://packages.element.io/debian/element-io-archive-keyring.gpg
+        echo "deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https://packages.element.io/debian/ default main" | $sudo tee /etc/apt/sources.list.d/element-io.list
+        $sudo apt-get update -y
+        $sudo apt-get install -y element-desktop || echo "element desktop install failed."
         echo "element desktop installed."
     fi
 }
@@ -105,9 +111,9 @@ install_github_desktop() {
     if command -v github-desktop >/dev/null 2>&1; then
         echo "github desktop already installed."
     else
-        sudo curl -L https://github.com/shiftkey/desktop/releases/download/release-3.4.3-linux1/GitHubDesktop-linux-${arch}-3.4.3-linux1.deb -o GitHubDesktop-linux-${arch}-3.4.3-linux1.deb
-        sudo dpkg -i GitHubDesktop-linux-${arch}-3.4.3-linux1.deb || echo "github desktop install failed."
-        sudo rm -f GitHubDesktop-linux-${arch}-3.4.3-linux1.deb
+        $sudo curl -L https://github.com/shiftkey/desktop/releases/download/release-3.4.3-linux1/GitHubDesktop-linux-${arch}-3.4.3-linux1.deb -o GitHubDesktop-linux-${arch}-3.4.3-linux1.deb
+        $sudo dpkg -i GitHubDesktop-linux-${arch}-3.4.3-linux1.deb || echo "github desktop install failed."
+        $sudo rm -f GitHubDesktop-linux-${arch}-3.4.3-linux1.deb
         echo "github desktop installed."
     fi
 }
@@ -129,9 +135,9 @@ install_ruby_fusuma() {
     if command -v fusuma >/dev/null 2>&1; then
         echo "fusuma already installed."
     elif command -v gem >/dev/null; then
-        sudo gem install fusuma || echo "fusuma install failed."
-        sudo groupadd -f input
-        sudo usermod -aG input "$(whoami)"
+        $sudo gem install fusuma || echo "fusuma install failed."
+        $sudo groupadd -f input
+        $sudo usermod -aG input "$(whoami)"
         fusuma -d
         echo "fusuma installed."
     else
@@ -143,9 +149,9 @@ install_tabby_terminal() {
     if command -v tabby >/dev/null 2>&1; then
         echo "tabby terminal already installed."
     else
-        curl https://packagecloud.io/install/repositories/eugeny/tabby/script.deb.sh | sudo bash
-        sudo apt-get update -y
-        sudo apt-get install -y tabby-terminal || echo "tabby terminal install failed."
+        curl https://packagecloud.io/install/repositories/eugeny/tabby/script.deb.sh | $sudo bash
+        $sudo apt-get update -y
+        $sudo apt-get install -y tabby-terminal || echo "tabby terminal install failed."
         echo "tabby terminal installed."
     fi
 }
@@ -154,12 +160,12 @@ install_vscode() {
     if command -v code >/dev/null 2>&1; then
         echo "vscode already installed."
     else
-        sudo wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor > packages.microsoft.gpg
-        sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
-        echo "deb [arch=${arch} signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
-        sudo rm -f packages.microsoft.gpg
-        sudo apt-get update -y
-        sudo apt-get install -y code || echo "vscode install failed."
+        $sudo wget -qO- https://packages.microsoft.com/keys/microsoft.asc | $sudo gpg --dearmor > packages.microsoft.gpg
+        $sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
+        echo "deb [arch=${arch} signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | $sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
+        $sudo rm -f packages.microsoft.gpg
+        $sudo apt-get update -y
+        $sudo apt-get install -y code || echo "vscode install failed."
         echo "vscode installed."
     fi
 }
@@ -168,10 +174,10 @@ install_wireshark() {
     if command -v wireshark >/dev/null 2>&1; then
         echo "wireshark already installed."
     else
-        sudo apt install -y wireshark || echo "wireshark install failed."
-        sudo groupadd -f wireshark
-        sudo usermod -aG wireshark "$(whoami)"
-        sudo chmod +x /usr/bin/dumpcap
+        $sudo apt install -y wireshark || echo "wireshark install failed."
+        $sudo groupadd -f wireshark
+        $sudo usermod -aG wireshark "$(whoami)"
+        $sudo chmod +x /usr/bin/dumpcap
         echo "wireshark installed."
     fi
 }
