bomm

diff --git a/home/.chezmoiscripts/linux/run_onchange_setup.sh.tmpl b/home/.chezmoiscripts/linux/run_onchange_setup.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_onchange_setup.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_onchange_setup.sh.tmpl
@@ -36,15 +36,15 @@ install_snap() {
 
     command -v speedtest >/dev/null || sudo snap install speedtest && echo "speedtest installed." || echo "speedtest install failed."
 
-    command -v codium >/dev/null || sudo snap install codium --classic && echo "codium installed." || echo "codium install failed."
+    # command -v chromium >/dev/null || sudo snap install chromium && echo "chromium installed." || echo "chromium install failed."
+
+    # command -v codium >/dev/null || sudo snap install codium --classic && echo "codium installed." || echo "codium install failed."
 
     command -v alacritty >/dev/null || sudo snap install alacritty --classic && echo "alacritty installed." || echo "alacritty install failed."
 
     if command -v firefox >/dev/null 2>&1; then
         sudo snap remove firefox || sudo apt remove firefox && echo "firefox uninstalled." || echo "firefox uninstall failed."
     fi
-
-    #command -v chromium >/dev/null || sudo snap install chromium && echo "chromium installed." || echo "chromium install failed."
 
     echo "snap tools installed."
 }
@@ -119,8 +119,8 @@ install_vscode() {
         sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
         echo "deb [arch=${arch} signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
         sudo rm -f packages.microsoft.gpg
-        sudo apt update -y
-        sudo apt install -y code || echo "vscode install failed."
+        sudo apt-get update -y
+        sudo apt-get install -y code || echo "vscode install failed."
         echo "vscode installed."
     else
         echo "vscode already installed."
