🍕

diff --git a/home/.chezmoiscripts/linux/run_onchange_after_snap.sh.tmpl b/home/.chezmoiscripts/linux/run_onchange_after_snap.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_onchange_after_snap.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_onchange_after_snap.sh.tmpl
@@ -8,7 +8,7 @@ fi
 
 install_snapd() {
     if ! command -v snap >/dev/null 2>&1; then
-        $sudo apt-get install -y snap snapd && echo "snapd installed." || echo "snapd install failed."
+        $sudo apt-get install -y snap snapd || echo "snapd install failed."
     else
         echo "snapd already installed."
     fi
@@ -18,23 +18,17 @@ install_snap() {
 
     {{ range .packages.snap.classic -}}
     if ! command -v {{ . }} >/dev/null 2>&1; then
-        $sudo snap install {{ . }} --classic && echo "{{ . }} installed." || echo "{{ . }} install failed."
-    else
+        $sudo snap install {{ . }} --classic || echo "{{ . }} install failed."
         echo "{{ . }} already installed."
     fi
     {{ end -}}
 
     {{ range .packages.snap.latest -}}
     if ! command -v {{ . }} >/dev/null 2>&1; then
-        $sudo snap install {{ . }} && echo "{{ . }} installed." || echo "{{ . }} install failed."
-    else
+        $sudo snap install {{ . }} || echo "{{ . }} install failed."
         echo "{{ . }} already installed."
     fi
     {{ end -}}
-
-    if command -v firefox >/dev/null 2>&1; then
-        $sudo snap remove firefox || $sudo apt remove firefox && echo "firefox uninstalled." || echo "firefox uninstall failed."
-    fi
 
     echo "snap tools installed."
 }
