👩

diff --git a/home/.chezmoiscripts/linux/run_onchange_after_gui.sh.tmpl b/home/.chezmoiscripts/linux/run_onchange_after_gui.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_onchange_after_gui.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_onchange_after_gui.sh.tmpl
@@ -64,7 +64,7 @@ install_cloudflare_warp() {
 ## 代変えインストーラー https://github.com/watzon/cursor-linux-installer
 install_cursor() {
     APP_DIR="${HOME}/Applications"
-    APP_IMAGE="${APP_DIR}/cursor.AppImage"
+    APP_IMAGE="${APP_DIR}/cursor"
     mkdir -p "${APP_DIR}"
 
     # cursor download アーキテクチャに応じて
@@ -82,7 +82,7 @@ install_cursor() {
     $sudo chmod a+x "${APP_IMAGE}"
 
     # libfuse2 が必要なのでインストール
-    sudo apt-get install -y libfuse2 || echo "libfuse2 install failed."
+    $sudo apt-get install -y libfuse2 || echo "libfuse2 install failed."
 
     # cursor の実行方法を表示
     echo 'use command: ${APP_IMAGE} --no-sandbox'
@@ -115,9 +115,9 @@ install_github_desktop() {
 
 install_ruby_fusuma() {
     # ruby のインストール
-    if command -v gem >/dev/null; then
+    if command -v gem >/dev/null 2>&1; then
         echo "ruby already installed."
-    elif command -v mise >/dev/null; then
+    elif command -v mise >/dev/null 2>&1; then
         mise use ruby -g -y || echo "ruby install failed."
         echo "ruby installed."
     else
@@ -129,7 +129,7 @@ install_ruby_fusuma() {
     # fusuma のインストール
     if command -v fusuma >/dev/null 2>&1; then
         echo "fusuma already installed."
-    elif command -v gem >/dev/null; then
+    elif command -v gem >/dev/null 2>&1; then
         $sudo gem install fusuma || echo "fusuma install failed."
         $sudo groupadd -f input
         $sudo usermod -aG input "$(whoami)"
diff --git a/home/.chezmoiscripts/linux/run_onchange_after_snap.sh.tmpl b/home/.chezmoiscripts/linux/run_onchange_after_snap.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_onchange_after_snap.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_onchange_after_snap.sh.tmpl
@@ -6,17 +6,17 @@ if [ "$(id -u)" -ne 0 ]; then
 fi
 
 install_snapd() {
-    command -v snap >/dev/null || $sudo apt-get install -y snap snapd && echo "snapd installed." || echo "snapd install failed."
+    command -v snap >/dev/null 2>&1 || $sudo apt-get install -y snap snapd && echo "snapd installed." || echo "snapd install failed."
 }
 
 install_snap() {
 
     {{ range .packages.snap.classic }}
-    command -v {{ . }} >/dev/null || $sudo snap install {{ . }} --classic && echo "{{ . }} installed." || echo "{{ . }} install failed."
+    command -v {{ . }} >/dev/null 2>&1 || $sudo snap install {{ . }} --classic && echo "{{ . }} installed." || echo "{{ . }} install failed."
     {{ end }}
 
     {{ range .packages.snap.latest }}
-    command -v {{ . }} >/dev/null || $sudo snap install {{ . }} && echo "{{ . }} installed." || echo "{{ . }} install failed."
+    command -v {{ . }} >/dev/null 2>&1 || $sudo snap install {{ . }} && echo "{{ . }} installed." || echo "{{ . }} install failed."
     {{ end }}
 
     if command -v firefox >/dev/null 2>&1; then
