dd

diff --git a/home/.chezmoiscripts/linux/run_once_after_docker.sh.tmpl b/home/.chezmoiscripts/linux/run_once_after_docker.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_once_after_docker.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_once_after_docker.sh.tmpl
@@ -12,15 +12,30 @@ install_docker() {
     if command -v docker >/dev/null 2>&1; then
         docker --version >> ${HOME}/which
     else
-        $sudo apt-get update -y
-        $sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release software-properties-common || echo "apt install failed."
-        $sudo mkdir -p /etc/apt/keyrings
-        $sudo install -m 0755 -d /etc/apt/keyrings
-        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | $sudo gpg --dearmor -o /etc/apt/keyrings/docker.asc
-        $sudo chmod a+r /etc/apt/keyrings/docker.asc
+        # $sudo apt-get update -y
+        # $sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release software-properties-common || echo "apt install failed."
+        # $sudo mkdir -p /etc/apt/keyrings
+        # $sudo install -m 0755 -d /etc/apt/keyrings
+        # curl -fsSL https://download.docker.com/linux/ubuntu/gpg | $sudo gpg --dearmor -o /etc/apt/keyrings/docker.asc
+        # $sudo chmod a+r /etc/apt/keyrings/docker.asc
         # echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | $sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
-        echo "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | $sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
-        $sudo apt-get update -y
+        # $sudo apt-get update -y
+        # $sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin || echo "docker install failed."
+
+        # Add Docker's official GPG key:
+        $sudo apt-get update
+        $sudo apt-get install -y ca-certificates curl
+        $sudo install -m 0755 -d /etc/apt/keyrings
+        $sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
+        $sudo chmod a+r /etc/apt/keyrings/docker.asc
+
+        # Add the repository to Apt sources:
+        echo \
+        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
+        $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
+        $sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+        $sudo apt-get update
+
         $sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin || echo "docker install failed."
 
         if [ -f /var/run/docker.sock ]; then
@@ -68,7 +83,7 @@ install_act() {
 }
 
 install_docker
-install_docker_compose
+# install_docker_compose
 install_act
 cat ${HOME}/which && rm -f ${HOME}/which
 echo "--------------------------------"
