iii

diff --git a/home/.chezmoiscripts/linux/run_once_docker_install.sh.tmpl b/home/.chezmoiscripts/linux/run_once_docker_install.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_once_docker_install.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_once_docker_install.sh.tmpl
@@ -3,21 +3,6 @@
 echo "run_once_docker_install.sh.tmpl"
 echo "--------------------------------"
 
-install_docker_compose() {
-    if command -v docker-compose >/dev/null 2>&1; then
-        docker-compose --version >> ${HOME}/which
-    else
-        # 最新バージョンを取得
-        COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)
-        # ダウンロード URL の作成
-        COMPOSE_URL="https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)"
-        # Docker Compose のバイナリをダウンロード
-        sudo curl -L "$COMPOSE_URL" -o /usr/local/bin/docker-compose || echo "docker-compose download failed."
-        sudo chmod +x /usr/local/bin/docker-compose
-        docker-compose --version >> ${HOME}/which || echo "docker-compose not found" >> ${HOME}/which
-    fi
-}
-
 install_docker() {
     if command -v docker >/dev/null 2>&1; then
         docker --version >> ${HOME}/which
@@ -39,6 +24,21 @@ install_docker() {
         sudo systemctl enable docker
         docker info
         docker --version >> ${HOME}/which || echo "docker not found" >> ${HOME}/which
+    fi
+}
+
+install_docker_compose() {
+    if command -v docker-compose >/dev/null 2>&1; then
+        docker-compose --version >> ${HOME}/which
+    else
+        # 最新バージョンを取得
+        COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)
+        # ダウンロード URL の作成
+        COMPOSE_URL="https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)"
+        # Docker Compose のバイナリをダウンロード
+        sudo curl -L "$COMPOSE_URL" -o /usr/local/bin/docker-compose || echo "docker-compose download failed."
+        sudo chmod +x /usr/local/bin/docker-compose
+        docker-compose --version >> ${HOME}/which || echo "docker-compose not found" >> ${HOME}/which
     fi
 }
 
