www

diff --git a/home/.chezmoiscripts/linux/run_once_after_setup.sh.tmpl b/home/.chezmoiscripts/linux/run_once_after_setup.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_once_after_setup.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_once_after_setup.sh.tmpl
@@ -10,33 +10,29 @@ fi
 
 japan_setup() {
     echo "japan setup start..."
-    #$sudo localectl set-locale LANG=ja_JP.UTF-8
-    #$sudo localectl set-locale LANGUAGE=ja_JP:ja
-    #$sudo localectl set-x11-keymap jp
-    #$sudo localectl set-keymap jp106
-    #$sudo timedatectl set-timezone Asia/Tokyo
-    #LANG=C xdg-user-dirs-update --force
-    # 入力メソッドとしてfcitx5を設定
+    $sudo localectl set-locale LANG=ja_JP.UTF-8
+    $sudo localectl set-locale LANGUAGE=ja_JP:ja
+    $sudo localectl set-x11-keymap jp
+    $sudo localectl set-keymap jp106
+    $sudo timedatectl set-timezone Asia/Tokyo
+    # LANG=C xdg-user-dirs-update --force
     $sudo im-config -n fcitx5
     echo "japan setup completed."
 }
 
 xrdp_setup() {
     echo "xrdp setup start..."
-    $sudo groupadd -f ssl-cert
-    $sudo groupadd -f xrdp
-    # ubuntuユーザーを必要なグループに追加
-    $sudo usermod -aG ssl-cert,xrdp "$(whoami)"
-    # サービスの再起動
-    $sudo systemctl daemon-reload
-    $sudo systemctl restart rsyslog
-    # ファイアウォールで3389番ポート（RDP）を許可
-    $sudo ufw allow 3389
-    # xrdpサービスを有効化
-    $sudo systemctl enable xrdp
     # デフォルトのセッションマネージャーをxfce4-sessionに設定
     $sudo update-alternatives --set x-session-manager /usr/bin/xfce4-session
-    # xrdpサービスを起動
+
+    $sudo groupadd -f ssl-cert
+    $sudo groupadd -f xrdp
+    $sudo usermod -aG ssl-cert,xrdp "$(whoami)"
+    $sudo ufw allow 3389
+
+    $sudo systemctl daemon-reload
+    $sudo systemctl restart rsyslog
+    $sudo systemctl enable xrdp
     $sudo systemctl start xrdp
     echo "xrdp setup completed."
 
@@ -49,13 +45,14 @@ xrdp_setup() {
 
 pipewire_setup() {
     doko=$(pwd)
+    pulseaudio_dir="${HOME}/.config/pulseaudio"
     pipewire_dir="${HOME}/.config/pipewire/pulseaudio-module-xrdp"
 
     # pulseaudio をインストール
-    $sudo apt-get install -y pulseaudio libpulse-dev dh-autoreconf dpkg-dev git && echo "pulseaudio installed." || echo "pulseaudio install failed."
+    $sudo apt-get install -y pulseaudio libpulse-dev dh-autoreconf dpkg-dev git || echo "pulseaudio install failed."
 
-    mkdir -p ~/.config/pulseaudio
-    cd ~/.config/pulseaudio
+    mkdir -p "${pulseaudio_dir}"
+    cd "${pulseaudio_dir}"
     git clone https://github.com/neutrinolabs/pulseaudio-module-xrdp.git
     cd pulseaudio-module-xrdp
     $sudo make install
