🌰

diff --git a/home/.chezmoiscripts/linux/run_onchange_after_gui.sh.tmpl b/home/.chezmoiscripts/linux/run_onchange_after_gui.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_onchange_after_gui.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_onchange_after_gui.sh.tmpl
@@ -61,31 +61,31 @@ install_cloudflare_warp() {
     fi
 }
 
+## 代変えインストーラー https://github.com/watzon/cursor-linux-installer
 install_cursor() {
-    # appimage用の Application ディレクトリの作成
-    appimage="${HOME}/Applications/cursor"
-    mkdir -p "${HOME}/Applications"
+    APP_DIR="${HOME}/Applications"
+    APP_IMAGE="${APP_DIR}/cursor.AppImage"
+    mkdir -p "${APP_DIR}"
 
     # cursor download アーキテクチャに応じて
-    if [ -f "${appimage}" ]; then
+    if [ -f "${APP_IMAGE}" ]; then
         echo "cursor already installed."
 
     elif [ "${arch}" = "amd64" ]; then
-        curl -L https://downloader.cursor.sh/inulx -o "${appimage}" || echo "cursor download failed."
+        curl -L https://downloads.cursor.com/production/d01860bc5f5a36b62f8a77cd42578126270db343/linux/x64/Cursor-1.4.2-x86_64.AppImage -o "${APP_IMAGE}" || echo "cursor download failed."
 
     elif [ "${arch}" = "arm64" ]; then
-        curl -L https://github.com/coder/cursor-arm/releases/download/v0.42.2/cursor_0.42.2_linux_arm64.AppImage -o "${appimage}" || echo "cursor download failed."
+        curl -L https://downloads.cursor.com/production/d01860bc5f5a36b62f8a77cd42578126270db343/linux/arm64/Cursor-1.4.2-aarch64.AppImage -o "${APP_IMAGE}" || echo "cursor download failed."
     fi
 
     # cursor の実行ファイルに実行権限を付与
-    $sudo chmod a+x "${appimage}"
+    $sudo chmod a+x "${APP_IMAGE}"
 
     # libfuse2 が必要なのでインストール
     sudo apt-get install -y libfuse2 || echo "libfuse2 install failed."
 
     # cursor の実行方法を表示
-    echo 'use command: ${appimage} --no-sandbox'
-
+    echo 'use command: ${APP_IMAGE} --no-sandbox'
     echo "cursor installed."
 }
 
