do

diff --git a/home/.chezmoiscripts/linux/run_onchange_gui_install.sh.tmpl b/home/.chezmoiscripts/linux/run_onchange_gui_install.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_onchange_gui_install.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_onchange_gui_install.sh.tmpl
@@ -10,16 +10,15 @@ arch="$(dpkg --print-architecture)"
 # デスクトップ環境のインストール
 # package は .chezmoidata/packages.yaml に記載
 # .packages.linux.gui にはxfceデスクトップ環境をインストールするパッケージを記載
+
 desktop_setup() {
     sudo apt-get update -y
     sudo apt-get upgrade -y
 
     {{ range .packages.linux.gui -}}
-
     if ! dpkg -l | grep -q {{ . }}; then
         sudo apt-get install -y {{ . }} || echo "{{ . }} install failed." >> ${HOME}/which
     fi
-
     {{ end }}
 
     #sudo apt-get remove -y light-locker xscreensaver &&
@@ -29,51 +28,22 @@ desktop_setup() {
     echo "desktop packages installed."
 }
 
-install_snap() {
-    command -v snap >/dev/null || sudo apt-get install -y snapd && echo "snapd installed." || echo "snapd install failed."
-
-    command -v multipass >/dev/null || sudo snap install multipass && echo "multipass installed." || echo "multipass install failed."
-
-    command -v speedtest >/dev/null || sudo snap install speedtest && echo "speedtest installed." || echo "speedtest install failed."
-
-    # command -v chromium >/dev/null || sudo snap install chromium && echo "chromium installed." || echo "chromium install failed."
-
-    # command -v codium >/dev/null || sudo snap install codium --classic && echo "codium installed." || echo "codium install failed."
-
-    command -v alacritty >/dev/null || sudo snap install alacritty --classic && echo "alacritty installed." || echo "alacritty install failed."
-
-    if command -v firefox >/dev/null 2>&1; then
-        sudo snap remove firefox || sudo apt remove firefox && echo "firefox uninstalled." || echo "firefox uninstall failed."
-    fi
-
-    echo "snap tools installed."
-}
-
 install_brave_browser() {
-    if ! command -v brave-browser >/dev/null 2>&1; then
+    if command -v brave-browser >/dev/null 2>&1; then
+        echo "brave browser already installed."
+    else
         sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
         echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
         sudo apt-get update -y
         sudo apt-get install -y brave-browser || echo "brave browser install failed."
         echo "brave browser installed."
-    else
-        echo "brave browser already installed."
-    fi
-}
-
-install_tabby_terminal() {
-    if ! command -v tabby >/dev/null 2>&1; then
-        curl https://packagecloud.io/install/repositories/eugeny/tabby/script.deb.sh | sudo bash
-        sudo apt-get update -y
-        sudo apt-get install -y tabby-terminal || echo "tabby terminal install failed."
-        echo "tabby terminal installed."
-    else
-        echo "tabby terminal already installed."
     fi
 }
 
 install_cloudflare_warp() {
-    if ! command -v warp-cli >/dev/null 2>&1; then
+    if command -v warp-cli >/dev/null 2>&1; then
+        echo "cloudflare warp already installed."
+    else
         sudo curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
         echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
         sudo apt-get update -y
@@ -85,36 +55,105 @@ install_cloudflare_warp() {
         warp-cli --accept-tos dns families malware
         warp-cli --accept-tos connect
         warp-cli --accept-tos disconnect
-    else
-        echo "cloudflare warp already installed."
+
+        echo "cloudflare warp installed."
     fi
 }
 
+install_cursor() {
+    # appimage用の Application ディレクトリの作成
+    appimage="${HOME}/Applications/cursor"
+    mkdir -p "${HOME}/Applications"
+
+    # cursor download アーキテクチャに応じて
+    if [ -f "${appimage}" ]; then
+        echo "cursor already installed."
+
+    elif [ "${arch}" = "amd64" ]; then
+        curl -L https://downloader.cursor.sh/inulx -o "${appimage}" || echo "cursor download failed."
+
+    elif [ "${arch}" = "arm64" ]; then
+        curl -L https://github.com/coder/cursor-arm/releases/download/v0.42.2/cursor_0.42.2_linux_arm64.AppImage -o "${appimage}" || echo "cursor download failed."
+    fi
+
+    # cursor の実行ファイルに実行権限を付与
+    sudo chmod a+x "${appimage}"
+
+    # libfuse2 が必要なのでインストール
+    sudo apt-get install -y libfuse2 || echo "libfuse2 install failed."
+
+    # cursor の実行方法を表示
+    echo 'use command: ${appimage} --no-sandbox'
+
+    echo "cursor installed."
+}
+
 install_element_desktop() {
-    if ! command -v element-desktop >/dev/null 2>&1; then
+    if command -v element-desktop >/dev/null 2>&1; then
+        echo "element desktop already installed."
+    else
         sudo apt-get install -y wget apt-transport-https
         sudo wget -O /usr/share/keyrings/element-io-archive-keyring.gpg https://packages.element.io/debian/element-io-archive-keyring.gpg
         echo "deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https://packages.element.io/debian/ default main" | sudo tee /etc/apt/sources.list.d/element-io.list
         sudo apt-get update -y
         sudo apt-get install -y element-desktop || echo "element desktop install failed."
-    else
-        echo "element desktop already installed."
+        echo "element desktop installed."
     fi
 }
 
 install_github_desktop() {
-    if ! command -v github-desktop >/dev/null 2>&1; then
+    if command -v github-desktop >/dev/null 2>&1; then
+        echo "github desktop already installed."
+    else
         sudo curl -L https://github.com/shiftkey/desktop/releases/download/release-3.4.3-linux1/GitHubDesktop-linux-${arch}-3.4.3-linux1.deb -o GitHubDesktop-linux-${arch}-3.4.3-linux1.deb
         sudo dpkg -i GitHubDesktop-linux-${arch}-3.4.3-linux1.deb || echo "github desktop install failed."
         sudo rm -f GitHubDesktop-linux-${arch}-3.4.3-linux1.deb
         echo "github desktop installed."
+    fi
+}
+
+install_ruby_fusuma() {
+    # ruby のインストール
+    if command -v gem >/dev/null; then
+        echo "ruby already installed."
+    elif command -v mise >/dev/null; then
+        mise use ruby -g -y || echo "ruby install failed."
+        echo "ruby installed."
     else
-        echo "github desktop already installed."
+        curl -sSL https://raw.githubusercontent.com/mise-tea/mise/master/get | bash || echo "mise install failed."
+        mise use ruby -g -y || echo "ruby install failed."
+        echo "ruby installed."
+    fi
+
+    # fusuma のインストール
+    if command -v fusuma >/dev/null 2>&1; then
+        echo "fusuma already installed."
+    elif command -v gem >/dev/null; then
+        sudo gem install fusuma || echo "fusuma install failed."
+        sudo groupadd -f input
+        sudo usermod -aG input "$(whoami)"
+        fusuma -d
+        echo "fusuma installed."
+    else
+        echo "gem command not found."
+    fi
+}
+
+install_tabby_terminal() {
+    if command -v tabby >/dev/null 2>&1; then
+        echo "tabby terminal already installed."
+    else
+        curl https://packagecloud.io/install/repositories/eugeny/tabby/script.deb.sh | sudo bash
+        sudo apt-get update -y
+        sudo apt-get install -y tabby-terminal || echo "tabby terminal install failed."
+        echo "tabby terminal installed."
     fi
 }
 
 install_vscode() {
-    if ! command -v code >/dev/null 2>&1; then
+    if command -v code >/dev/null 2>&1; then
+        echo "vscode already installed."
+    else
         sudo wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor > packages.microsoft.gpg
         sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
         echo "deb [arch=${arch} signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
@@ -122,63 +161,31 @@ install_vscode() {
         sudo apt-get update -y
         sudo apt-get install -y code || echo "vscode install failed."
         echo "vscode installed."
-    else
-        echo "vscode already installed."
     fi
-}
-
-install_cursor() {
-    appimage="${HOME}/Applications/cursor"
-    mkdir -p "${HOME}/Applications"
-    if ! [ -f "${appimage}" ]; then
-        if [ "${arch}" = "amd64" ]; then
-            curl -L https://downloader.cursor.sh/inulx -o "${appimage}" || echo "cursor download failed."
-        else
-            curl -L https://github.com/coder/cursor-arm/releases/download/v0.42.2/cursor_0.42.2_linux_arm64.AppImage -o "${appimage}" || echo "cursor download failed."
-        fi
-    fi
-    sudo chmod a+x "${appimage}"
-    sudo apt-get install -y libfuse2 || echo "libfuse2 install failed."
-    echo "${appimage} installed."
 }
 
 install_wireshark() {
-    if ! command -v wireshark >/dev/null 2>&1; then
+    if command -v wireshark >/dev/null 2>&1; then
+        echo "wireshark already installed."
+    else
         sudo apt install -y wireshark || echo "wireshark install failed."
         sudo groupadd -f wireshark
         sudo usermod -aG wireshark "$(whoami)"
         sudo chmod +x /usr/bin/dumpcap
         echo "wireshark installed."
-    else
-        echo "wireshark already installed."
-    fi
-}
-
-install_ruby_fusuma() {
-    command -v gem >/dev/null || mise use ruby -g -y || sudo apt-get install -y ruby || echo "ruby install failed."
-    echo "ruby installed."
-
-    if ! command -v fusuma >/dev/null 2>&1; then
-        sudo gem install fusuma || echo "fusuma install failed."
-        sudo groupadd -f input
-        sudo usermod -aG input "$(whoami)"
-        fusuma -d
-        echo "fusuma installed."
-    else
-        echo "fusuma already installed."
     fi
 }
 
 echo "ubuntu desktop setup start..."
 desktop_setup
 install_brave_browser
-install_tabby_terminal
 install_cloudflare_warp
-install_github_desktop
-install_vscode
 install_cursor
 install_element_desktop
+install_github_desktop
 install_ruby_fusuma
+install_tabby_terminal
+install_vscode
 # install_wireshark
 echo "ubuntu desktop setup completed."
 neofetch
diff --git a/home/.chezmoiscripts/linux/run_onchange_snap.sh.tmpl b/home/.chezmoiscripts/linux/run_onchange_snap.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_onchange_snap.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_onchange_snap.sh.tmpl
@@ -1,92 +1,35 @@
 #!/usr/bin/env bash
 
-echo "run_once_snap.sh.tmpl"
+echo "run_onchange_snap.sh.tmpl"
 echo "--------------------------------"
 
+if $(whoami) != "root"; then
+    sudo="sudo"
+else
+    sudo=""
+fi
+
+install_snapd() {
+    command -v snap >/dev/null || $sudo apt-get install -y snapd && echo "snapd installed." || echo "snapd install failed."
+}
+
 install_snap() {
-    command -v snap >/dev/null || sudo apt-get install -y snapd && echo "snapd installed." || echo "snapd install failed."
 
-    command -v multipass >/dev/null || sudo snap install multipass && echo "multipass installed." || echo "multipass install failed."
+    {{ range .packages.linux.snap.classic -}}
+    command -v {{ . }} >/dev/null || $sudo snap install {{ . }} --classic && echo "{{ . }} installed." || echo "{{ . }} install failed."
+    {{ end }}
 
-    command -v speedtest >/dev/null || sudo snap install speedtest && echo "speedtest installed." || echo "speedtest install failed."
-
-    # command -v chromium >/dev/null || sudo snap install chromium && echo "chromium installed." || echo "chromium install failed."
-
-    # command -v codium >/dev/null || sudo snap install codium --classic && echo "codium installed." || echo "codium install failed."
-
-    command -v alacritty >/dev/null || sudo snap install alacritty --classic && echo "alacritty installed." || echo "alacritty install failed."
+    {{ range .packages.linux.snap.latest -}}
+    command -v {{ . }} >/dev/null || $sudo snap install {{ . }} && echo "{{ . }} installed." || echo "{{ . }} install failed."
+    {{ end }}
 
     if command -v firefox >/dev/null 2>&1; then
-        sudo snap remove firefox || sudo apt remove firefox && echo "firefox uninstalled." || echo "firefox uninstall failed."
+        sudo snap remove firefox || $sudo apt remove firefox && echo "firefox uninstalled." || echo "firefox uninstall failed."
     fi
 
     echo "snap tools installed."
 }
 
-japan_setup() {
-    echo "japan setup start..."
-    #sudo localectl set-locale LANG=ja_JP.UTF-8
-    #sudo localectl set-locale LANGUAGE=ja_JP:ja
-    #sudo localectl set-x11-keymap jp
-    #sudo localectl set-keymap jp106
-    #sudo timedatectl set-timezone Asia/Tokyo
-    LANG=C xdg-user-dirs-update --force
-    # 入力メソッドとしてfcitx5を設定
-    im-config -n fcitx5
-    echo "japan setup completed."
-}
-
-install_pipewire() {
-    doko=$(pwd)
-    pipewire_dir="${HOME}/.config/pipewire/pulseaudio-module-xrdp"
-
-    # pulseaudio をインストール
-    sudo apt-get install -y pulseaudio libpulse-dev dh-autoreconf dpkg-dev && echo "pulseaudio installed." || echo "pulseaudio install failed."
-
-    # pipewire をインストール
-    sudo apt-get install -y pipewire pipewire-audio libspa-0.2-dev libpipewire-0.3-dev autoconf libtool && echo "pipewire installed." || echo "pipewire install failed."
-    mkdir -p "${HOME}/.config/pipewire"
-
-    if [ ! -d "${pipewire_dir}" ]; then
-        git clone https://github.com/neutrinolabs/pulseaudio-module-xrdp.git "${pipewire_dir}"
-        cd "${pipewire_dir}"
-        ./bootstrap
-        ./configure PULSE_DIR=$(cd ..; pwd)
-        make
-        sudo make install
-        cd "${doko}"
-    fi
-    echo "pipewire installed."
-}
-
-xrdp_setup() {
-    echo "xrdp setup start..."
-    sudo groupadd -f ssl-cert
-    sudo groupadd -f xrdp
-    # ubuntuユーザーを必要なグループに追加
-    sudo usermod -aG ssl-cert,xrdp "$(whoami)"
-    # サービスの再起動
-    sudo systemctl daemon-reload
-    sudo systemctl restart rsyslog
-    # ファイアウォールで3389番ポート（RDP）を許可
-    sudo ufw allow 3389
-    # xrdpサービスを有効化
-    sudo systemctl enable xrdp
-    # デフォルトのセッションマネージャーをxfce4-sessionに設定
-    sudo update-alternatives --set x-session-manager /usr/bin/xfce4-session
-    # xrdpサービスを起動
-    sudo systemctl start xrdp
-    echo "xrdp setup completed."
-
-    echo "以下のコマンドを実行してパスワードを更新してください"
-    echo "sudo passwd $(whoami)"
-    # ログイン後、ubuntuユーザーのパスワードを再設定を推奨
-    # パスワードを再設定しないとログインできない
-    # echo "$(whoami):$(whoami)" | sudo chpasswd
-}
-
+install_snapd
 install_snap
-install_pipewire
-japan_setup
-xrdp_setup
 echo "--------------------------------"
