ppp

diff --git a/home/.chezmoiscripts/linux/run_onchange_after_cli.sh.tmpl b/home/.chezmoiscripts/linux/run_onchange_after_cli.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_onchange_after_cli.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_onchange_after_cli.sh.tmpl
@@ -104,19 +104,16 @@ install_mise() {
 }
 
 install_cargo_tools() {
-    echo "cargo install start..."
     if command -v cargo >/dev/null; then
         echo "cargo already installed."
-
     elif command -v mise >/dev/null 2>&1; then
         mise use -g -y rust@stable || echo "cargo install failed."
-
     elif command -v curl >/dev/null 2>&1; then
         curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y || echo "cargo install failed."
-
+    elif command -v apt >/dev/null 2>&1; then
+        $sudo apt-get install -y cargo || echo "cargo install failed."
     else
         echo "curl not found"
-        $sudo apt-get install -y cargo || echo "cargo install failed."
     fi
 
     if [ -f ${HOME}/.cargo/env ]; then
@@ -125,17 +122,12 @@ install_cargo_tools() {
 
     cargo --version >> ${HOME}/which || echo "cargo not found" >> ${HOME}/which
 
-    echo "cargo tools install start..."
-
     if command -v cargo-binstall >/dev/null; then
         echo "cargo-binstall already installed."
-
     elif command -v mise >/dev/null; then
-        mise use -g -y cargo-binstall || echo "cargo tools install failed."
-
+        mise use -g -y cargo-binstall@latest || echo "cargo tools install failed."
     elif command -v cargo >/dev/null; then
-        cargo install cargo-binstall@1.6.9 --locked || echo "cargo tools install failed."
-
+        cargo install cargo-binstall || echo "cargo tools install failed."
     else
         echo "cargo not found" >> ${HOME}/which
     fi
@@ -143,13 +135,14 @@ install_cargo_tools() {
     {{ range .packages.cargo }}
 
     if command -v cargo-binstall >/dev/null; then
-        cargo-binstall {{ . }} || echo "{{ . }} install failed."
+        cargo-binstall {{ . }} -y || echo "{{ . }} install failed."
+        # cargo-binstall {{ . }} || echo "{{ . }} install failed."
     elif command -v cargo >/dev/null; then
-        cargo install {{ . }} || echo "{{ . }} install failed."
+        cargo install {{ . }} -y || echo "{{ . }} install failed."
     else
         echo "cargo not found"
     fi
-    echo "$(command -v {{ . }})" >> ${HOME}/which
+    echo "$(command -v {{ . }})" >> ${HOME}/which || echo "{{ . }} not found" >> ${HOME}/which
 
     {{ end }}
 
@@ -172,8 +165,10 @@ install_go_aqua() {
         echo "go already installed."
     elif command -v mise >/dev/null; then
         mise use -g -y go@latest || echo "go install failed."
-    else
+    elif command -v apt >/dev/null 2>&1; then
         $sudo apt-get install -y golang || echo "go install failed."
+    else
+        echo "go not found"
     fi
     go version >> ${HOME}/which || echo "go not found" >> ${HOME}/which
 
@@ -190,19 +185,22 @@ install_go_aqua() {
 }
 
 install_mkcert() {
-    echo "mkcert install start..."
     if command -v mkcert >/dev/null; then
         echo "mkcert already installed."
-
     elif command -v mise >/dev/null; then
-        mise use -g mkcert -y || echo "mkcert install failed."
-
-    else
+        mise use -g -y mkcert@latest || echo "mkcert install failed."
+    elif command -v apt >/dev/null 2>&1; then
         $sudo apt install -y mkcert || echo "mkcert install failed."
+    else
+        echo "mkcert not found"
     fi
 
-    mkcert -install || echo "mkcert not setup"
-    mkcert --version >> ${HOME}/which || echo "mkcert not found" >> ${HOME}/which
+    if command -v mkcert >/dev/null; then
+        mkcert -install || echo "mkcert not setup"
+        mkcert --version >> ${HOME}/which || echo "mkcert not found" >> ${HOME}/which
+    else
+        echo "mkcert not found"
+    fi
 }
 
 install_packages
